/** Admin panel copy — isolated from public i18n to avoid touching consumer-facing pages. */
export const adminCopy = {
  shell: {
    cmsEyebrow: "BrewAtlas Admin",
    topNavEyebrow: "Administration",
    topNavTitle: "Platform Console",
    sidebarAriaLabel: "Admin navigation",
    openMenuAria: "Open navigation menu",
    closeMenuAria: "Close navigation menu",
    backToSite: "Back to public site",
    myAccount: "My account",
    viewSite: "View public site",
    signOut: "Sign out",
    userMenuLabel: "Account",
  },
  nav: {
    dashboard: "Dashboard",
    homepage: "Homepage",
    heroBanners: "Hero Banners",
    featuredRecipes: "Featured Recipes",
    homepageSections: "Homepage Sections",
    users: "Users",
    recipes: "Recipes",
    media: "Images",
    devices: "Devices",
    origins: "Coffee Origins",
    roasters: "Roasters",
    reviews: "Reviews",
    subscriptions: "Subscriptions",
    analytics: "Analytics",
  },
  dashboard: {
    eyebrow: "Admin Dashboard",
    title: "Platform Overview",
    description: "Monitor users, content, subscriptions, and platform activity from one console.",
    totalUsers: "Total Users",
    premiumUsers: "Premium Users",
    recipes: "Recipes",
    monthlyRevenue: "Monthly Revenue",
    monthlyRevenueHint: "Estimated from active premium subscriptions",
    activeUsers30d: "Active Users (30d)",
    recipeViews: "Recipe Views",
    reviews: "Reviews",
    collections: "Collections",
    brewers: "Active Brewers",
    coffeeOrigins: "Coffee Origins",
    recipeSaves: "Recipe Saves",
    flaggedReviews: "Flagged Reviews",
    userGrowthChartTitle: "User Growth",
    userGrowthChartDescription: "Monthly trend based on current totals",
    recipeGrowthChartTitle: "Subscription Growth",
    recipeGrowthChartDescription: "Premium subscribers over time",
    revenueChartTitle: "Revenue Trend",
    revenueChartDescription: "Estimated monthly recurring revenue",
    recentActivityTitle: "Recent Activity",
    recentActivityEmpty: "No recent activity yet.",
    viewAllUsers: "Manage users",
    cmsSectionsTitle: "Content modules",
    cmsSectionsDescription: "Each module will become part of the BrewAtlas CMS.",
  },
  users: {
    title: "Users",
    description: "Search, review, and manage BrewAtlas accounts.",
    searchLabel: "Search users",
    searchPlaceholder: "Search by name, country, or email…",
    filterStatus: "Account status",
    filterAll: "All accounts",
    filterActive: "Active",
    filterSuspended: "Suspended",
    applyFilters: "Apply filters",
    noUsersTitle: "No users found",
    noUsersDescription: "Try adjusting your search or filters.",
    columnUser: "User",
    columnEmail: "Email",
    columnRole: "Role",
    columnPlan: "Plan",
    columnActivity: "Activity",
    columnStatus: "Status",
    columnJoined: "Joined",
    columnActions: "Actions",
    anonymousUser: "Anonymous user",
    noCountry: "No country",
    recipesCountTemplate: "{count} recipes",
    reviewsCountTemplate: "{count} reviews",
    statusSuspended: "Suspended",
    statusActive: "Active",
    viewProfile: "View profile",
    promoteAction: "Make admin",
    demoteAction: "Remove admin",
    demoteSelfBlocked: "You cannot remove your own admin access.",
    promoteConfirm: "Promote this user to admin?",
    demoteConfirm: "Remove admin access from this user?",
    suspendAction: "Suspend",
    restoreAction: "Restore",
    suspendReasonPlaceholder: "Reason (optional)",
    confirmSuspend: "Confirm suspend",
    ownerRoleNote: "CMS owner",
    pageTemplate: "Page {page} of {total}",
    previousPage: "Previous",
    nextPage: "Next",
  },
  sectionPlaceholder: {
    comingSoon: "Coming soon",
    descriptionTemplate:
      "This module will let admins manage {section} from the BrewAtlas CMS. The navigation and routing are in place for future content tools.",
    openOwnerCms: "Open legacy CMS",
    ownerCmsHint: "Content editing is still available in the owner dashboard until this module ships.",
  },
  subscriptions: {
    title: "Subscriptions",
    description: "Review membership plans and subscription status across the platform.",
  },
  analytics: {
    title: "Analytics",
    description: "Platform metrics, growth trends, and engagement insights.",
  },
  settings: {
    title: "Settings",
    description: "Platform configuration, featured content, and homepage controls.",
  },
  cms: {
    sharedTable: {
      searchPlaceholder: "Search…",
      filterAll: "All",
      filterPublished: "Published",
      filterDraft: "Unpublished",
      applyFilters: "Apply filters",
      create: "Create",
      edit: "Edit",
      delete: "Delete",
      publish: "Publish",
      unpublish: "Unpublish",
      noResults: "No items found.",
      previousPage: "Previous",
      nextPage: "Next",
      pageTemplate: "Page {page} of {total}",
      deleteConfirm: "Delete this item permanently?",
      statusPublished: "Published",
      statusDraft: "Draft",
    },
    devices: {
      title: "Devices",
      description: "Manage brewing devices and equipment referenced by recipes.",
      createTitle: "New device",
      editTitle: "Edit device",
      columnName: "Name",
      columnSlug: "Slug",
      columnManufacturer: "Manufacturer",
      table: {
        searchPlaceholder: "Search devices…",
        filterAll: "All",
        filterPublished: "Published",
        filterDraft: "Unpublished",
        applyFilters: "Apply filters",
        create: "New device",
        edit: "Edit",
        delete: "Delete",
        publish: "Publish",
        unpublish: "Unpublish",
        noResults: "No devices found.",
        previousPage: "Previous",
        nextPage: "Next",
        pageTemplate: "Page {page} of {total}",
        deleteConfirm: "Delete this device?",
        statusPublished: "Published",
        statusDraft: "Draft",
      },
      form: {
        name: "Name",
        slug: "Slug",
        manufacturer: "Manufacturer",
        published: "Published on site",
        save: "Save device",
        create: "Create device",
        delete: "Delete device",
        deleteConfirm: "Delete this device permanently?",
      },
    },
    origins: {
      title: "Coffee Origins",
      description: "Manage coffee-growing regions and origin profiles.",
      createTitle: "New origin",
      editTitle: "Edit origin",
      columnCountry: "Country",
      columnRegion: "Region",
      table: {
        searchPlaceholder: "Search origins…",
        filterAll: "All",
        filterPublished: "Published",
        filterDraft: "Unpublished",
        applyFilters: "Apply filters",
        create: "New origin",
        edit: "Edit",
        delete: "Delete",
        publish: "Publish",
        unpublish: "Unpublish",
        noResults: "No origins found.",
        previousPage: "Previous",
        nextPage: "Next",
        pageTemplate: "Page {page} of {total}",
        deleteConfirm: "Delete this origin?",
        statusPublished: "Published",
        statusDraft: "Draft",
      },
      form: {
        country: "Country",
        region: "Region",
        description: "Description",
        published: "Published on site",
        save: "Save origin",
        create: "Create origin",
        delete: "Delete origin",
        deleteConfirm: "Delete this origin permanently?",
      },
    },
    roasters: {
      title: "Roasters",
      description: "Manage roaster listings, logos, and featured partners.",
      createTitle: "New roaster",
      editTitle: "Edit roaster",
      columnName: "Name",
      columnCountry: "Country",
      columnFeatured: "Featured",
      table: {
        searchPlaceholder: "Search roasters…",
        filterAll: "All",
        filterPublished: "Published",
        filterDraft: "Unpublished",
        applyFilters: "Apply filters",
        create: "New roaster",
        edit: "Edit",
        delete: "Delete",
        publish: "Publish",
        unpublish: "Unpublish",
        noResults: "No roasters found.",
        previousPage: "Previous",
        nextPage: "Next",
        pageTemplate: "Page {page} of {total}",
        deleteConfirm: "Delete this roaster?",
        statusPublished: "Published",
        statusDraft: "Draft",
      },
      form: {
        name: "Name",
        slug: "Slug",
        country: "Country",
        website: "Website",
        logoUrl: "Logo URL",
        description: "Description",
        emirate: "Emirate",
        city: "City",
        featured: "Featured roaster",
        isUae: "UAE roaster",
        published: "Published on site",
        save: "Save roaster",
        create: "Create roaster",
        delete: "Delete roaster",
        deleteConfirm: "Delete this roaster permanently?",
      },
    },
    homepage: {
      title: "Homepage",
      description: "Manage public homepage content without code changes.",
      heroLink: "Hero banners",
      heroDescription: "Primary hero images and calls-to-action.",
      featuredLink: "Featured recipes",
      featuredDescription: "Recipe cards shown on the homepage.",
      sectionsLink: "Homepage sections",
      sectionsDescription: "Brew methods, origins showcase, roasters, testimonials, pricing, and FAQs.",
      mediaLink: "Image library",
      mediaDescription: "Upload and manage images used across the site.",
    },
    hero: {
      title: "Hero Banners",
      description: "Manage homepage hero banners and primary imagery.",
      createTitle: "New hero banner",
      columnTitle: "Title",
      columnLocale: "Locale",
    },
    featured: {
      title: "Featured Recipes",
      description: "Curate the recipe cards displayed on the homepage.",
      createTitle: "Add featured recipe",
    },
    sections: {
      title: "Homepage Sections",
      description: "Edit structured homepage section content (JSON arrays per section).",
    },
    media: {
      title: "Images",
      description: "Upload, organize, and manage the BrewAtlas media library.",
    },
  },
} as const;

export type AdminCopy = typeof adminCopy;
