import type { BrewMethodKey } from "@/lib/gulf-directory/placeholder-library/method-templates";
import type { Difficulty } from "@/types/homepage";

/** Compact recipe seed — expanded via method templates + roaster lookup. */
export type RecipeSeed = {
  slug: string;
  name: string;
  roasterSlug: string;
  methodKey: BrewMethodKey;
  difficulty: Difficulty;
  coffeeBeans: string;
  roastLevel: string;
  origin: string;
  process: string;
  tastingNotes: string;
  flavorTags: string[];
  lead: string;
  rating: number;
};

/**
 * Full Gulf placeholder recipe library.
 * Every recipe attaches to an existing PLACEHOLDER_ROASTERS slug.
 * Methods covered across the library: V60 hot/iced, Origami hot/iced,
 * Kalita Wave, AeroPress, Chemex, Espresso, Cold Brew.
 */
export const RECIPE_SEEDS: RecipeSeed[] = [
  // ── RAW Coffee Company ──
  {
    slug: "raw-v60-ethiopian",
    name: "RAW Ethiopian V60",
    roasterSlug: "raw-coffee-company",
    methodKey: "v60-hot",
    difficulty: "Intermediate",
    coffeeBeans: "Ethiopia Guji Washed",
    roastLevel: "Light",
    origin: "Guji, Ethiopia",
    process: "Washed",
    tastingNotes: "Jasmine, bergamot, white peach, and raw cane sugar with a tea-like body.",
    flavorTags: ["Floral", "Citrus", "Tea-like", "Clean"],
    lead: "A bright, tea-like V60 profile tuned for RAW’s washed Ethiopian lots.",
    rating: 4.8,
  },
  {
    slug: "raw-colombia-flash-brew",
    name: "RAW Colombia Flash Brew",
    roasterSlug: "raw-coffee-company",
    methodKey: "v60-iced",
    difficulty: "Intermediate",
    coffeeBeans: "Colombia Huila Washed",
    roastLevel: "Light-medium",
    origin: "Huila, Colombia",
    process: "Washed",
    tastingNotes: "Red apple, panela, and soft citrus over ice with sparkling clarity.",
    flavorTags: ["Apple", "Panela", "Bright", "Refreshing"],
    lead: "A V60 iced flash brew that locks in Colombia’s sweetness before the ice chill.",
    rating: 4.7,
  },
  {
    slug: "raw-kenya-origami",
    name: "RAW Kenya Origami",
    roasterSlug: "raw-coffee-company",
    methodKey: "origami-hot",
    difficulty: "Advanced",
    coffeeBeans: "Kenya AA Washed",
    roastLevel: "Light",
    origin: "Nyeri, Kenya",
    process: "Washed",
    tastingNotes: "Blackcurrant, grapefruit, and brown sugar with a juicy finish.",
    flavorTags: ["Blackcurrant", "Citrus", "Juicy", "Complex"],
    lead: "An Origami hot brew that keeps Kenya’s acidity articulate and sweet.",
    rating: 4.8,
  },
  {
    slug: "raw-house-espresso",
    name: "RAW House Espresso",
    roasterSlug: "raw-coffee-company",
    methodKey: "espresso",
    difficulty: "Advanced",
    coffeeBeans: "RAW House Blend",
    roastLevel: "Medium",
    origin: "Brazil & Ethiopia blend",
    process: "Natural / Washed",
    tastingNotes: "Dark chocolate, almond, and caramel with a syrupy body.",
    flavorTags: ["Chocolate", "Nutty", "Caramel", "Balanced"],
    lead: "A syrupy espresso dialed for café consistency and milk drinks.",
    rating: 4.7,
  },

  // ── The Espresso Lab ──
  {
    slug: "espresso-lab-competition-v60",
    name: "Espresso Lab Competition V60",
    roasterSlug: "the-espresso-lab",
    methodKey: "v60-hot",
    difficulty: "Advanced",
    coffeeBeans: "Competition Seasonal Lot",
    roastLevel: "Light",
    origin: "Ethiopia / rotating",
    process: "Washed",
    tastingNotes: "Bergamot, peach nectar, and cane sugar with laser clarity.",
    flavorTags: ["Bergamot", "Peach", "Competition", "Clean"],
    lead: "A competition-leaning V60 structure built for sweetness and clarity.",
    rating: 4.9,
  },
  {
    slug: "espresso-lab-house-v60-iced",
    name: "Espresso Lab House V60 Iced",
    roasterSlug: "the-espresso-lab",
    methodKey: "v60-iced",
    difficulty: "Intermediate",
    coffeeBeans: "Espresso Lab Filter Lot",
    roastLevel: "Light-medium",
    origin: "Colombia",
    process: "Washed",
    tastingNotes: "Honeydew, lime zest, and soft florals over ice.",
    flavorTags: ["Melon", "Citrus", "Floral", "Iced"],
    lead: "A house V60 iced flash brew for Dubai’s warm afternoons.",
    rating: 4.6,
  },
  {
    slug: "espresso-lab-signature",
    name: "Espresso Lab Signature",
    roasterSlug: "the-espresso-lab",
    methodKey: "espresso",
    difficulty: "Advanced",
    coffeeBeans: "Espresso Lab House Blend",
    roastLevel: "Medium",
    origin: "Brazil & Ethiopia blend",
    process: "Natural / Washed",
    tastingNotes: "Dark chocolate, almond brittle, red apple, and lingering caramel.",
    flavorTags: ["Chocolate", "Nutty", "Caramel", "Balanced"],
    lead: "The Lab’s signature espresso — sweet, dense, and milk-friendly.",
    rating: 4.7,
  },

  // ── Seven Fortunes ──
  {
    slug: "seven-fortunes-natural-ethiopia",
    name: "Seven Fortunes Natural Ethiopia",
    roasterSlug: "seven-fortunes",
    methodKey: "v60-hot",
    difficulty: "Beginner",
    coffeeBeans: "Ethiopia Natural",
    roastLevel: "Light",
    origin: "Sidama, Ethiopia",
    process: "Natural",
    tastingNotes: "Blueberry jam, cocoa, and florals with a soft body.",
    flavorTags: ["Blueberry", "Cocoa", "Floral", "Sweet"],
    lead: "An approachable V60 for fruity naturals with a sweet, clean finish.",
    rating: 4.5,
  },
  {
    slug: "seven-fortunes-washed-colombia",
    name: "Seven Fortunes Washed Colombia",
    roasterSlug: "seven-fortunes",
    methodKey: "chemex",
    difficulty: "Intermediate",
    coffeeBeans: "Colombia Washed",
    roastLevel: "Light-medium",
    origin: "Huila, Colombia",
    process: "Washed",
    tastingNotes: "Caramel, soft citrus, and cocoa nib with Chemex clarity.",
    flavorTags: ["Caramel", "Citrus", "Cocoa", "Clean"],
    lead: "A refined Chemex cup showcasing washed Colombia sweetness.",
    rating: 4.4,
  },

  // ── Cypher ──
  {
    slug: "cypher-cold-brew",
    name: "Cypher Cold Brew",
    roasterSlug: "cypher-roastery",
    methodKey: "cold-brew",
    difficulty: "Beginner",
    coffeeBeans: "Cypher Seasonal Natural",
    roastLevel: "Medium-light",
    origin: "Colombia / Ethiopia rotating",
    process: "Natural / Experimental",
    tastingNotes: "Cocoa nib, ripe berry, brown sugar, and a soft rounded mouthfeel.",
    flavorTags: ["Chocolate", "Berry", "Smooth", "Low acid"],
    lead: "A low-acid overnight immersion cold brew for Cypher’s experimental lots.",
    rating: 4.6,
  },
  {
    slug: "cypher-chemex-experimental",
    name: "Cypher Experimental Chemex",
    roasterSlug: "cypher-roastery",
    methodKey: "chemex",
    difficulty: "Advanced",
    coffeeBeans: "Anaerobic Seasonal",
    roastLevel: "Light",
    origin: "Colombia",
    process: "Anaerobic natural",
    tastingNotes: "Passionfruit, cacao husk, and tropical sweetness with a long finish.",
    flavorTags: ["Tropical", "Experimental", "Cacao", "Bold"],
    lead: "A Chemex framework that keeps wild process notes articulate.",
    rating: 4.5,
  },

  // ── Boom / Gold Box / Nightjar ──
  {
    slug: "boom-aeropress-house",
    name: "Boom House AeroPress",
    roasterSlug: "boom-coffee",
    methodKey: "aeropress",
    difficulty: "Beginner",
    coffeeBeans: "Boom House Blend",
    roastLevel: "Medium",
    origin: "Brazil & Central America",
    process: "Natural / Washed",
    tastingNotes: "Milk chocolate, toasted almond, and soft spice.",
    flavorTags: ["Chocolate", "Nutty", "Easy", "Everyday"],
    lead: "A forgiving AeroPress recipe for Sharjah weekday mornings.",
    rating: 4.3,
  },
  {
    slug: "boom-espresso-everyday",
    name: "Boom Everyday Espresso",
    roasterSlug: "boom-coffee",
    methodKey: "espresso",
    difficulty: "Beginner",
    coffeeBeans: "Boom House Blend",
    roastLevel: "Medium",
    origin: "Brazil & Central America",
    process: "Natural / Washed",
    tastingNotes: "Cocoa, brown sugar, and a gentle nutty finish.",
    flavorTags: ["Cocoa", "Sweet", "Milk-friendly"],
    lead: "Everyday espresso for balanced milk drinks and straight shots.",
    rating: 4.2,
  },
  {
    slug: "gold-box-kalita-microlot",
    name: "Gold Box Microlot Kalita",
    roasterSlug: "gold-box-roastery",
    methodKey: "kalita",
    difficulty: "Intermediate",
    coffeeBeans: "Seasonal Microlot",
    roastLevel: "Light",
    origin: "Rotating specialty origin",
    process: "Washed",
    tastingNotes: "White florals, honey, and stone fruit with a silky body.",
    flavorTags: ["Floral", "Honey", "Stone fruit", "Silky"],
    lead: "A Kalita Wave profile that protects delicate microlot aromatics.",
    rating: 4.5,
  },
  {
    slug: "gold-box-origami-iced",
    name: "Gold Box Origami Iced",
    roasterSlug: "gold-box-roastery",
    methodKey: "origami-iced",
    difficulty: "Intermediate",
    coffeeBeans: "Boutique Seasonal Lot",
    roastLevel: "Light",
    origin: "Ethiopia / Colombia rotating",
    process: "Washed",
    tastingNotes: "Citrus zest, jasmine, and cane sugar over ice.",
    flavorTags: ["Citrus", "Floral", "Iced", "Bright"],
    lead: "An Origami iced brew for boutique lots — sparkling and sweet.",
    rating: 4.4,
  },
  {
    slug: "nightjar-v60-precision",
    name: "Nightjar Precision V60",
    roasterSlug: "nightjar-coffee",
    methodKey: "v60-hot",
    difficulty: "Intermediate",
    coffeeBeans: "Nightjar Seasonal Filter",
    roastLevel: "Light-medium",
    origin: "Rotating",
    process: "Washed",
    tastingNotes: "Red apple, caramel, and soft florals with structured sweetness.",
    flavorTags: ["Apple", "Caramel", "Floral", "Structured"],
    lead: "A precision filter recipe with a sweet, structured cup.",
    rating: 4.5,
  },
  {
    slug: "nightjar-espresso",
    name: "Nightjar Espresso",
    roasterSlug: "nightjar-coffee",
    methodKey: "espresso",
    difficulty: "Advanced",
    coffeeBeans: "Nightjar Espresso Blend",
    roastLevel: "Medium",
    origin: "Brazil & East Africa",
    process: "Natural / Washed",
    tastingNotes: "Cocoa, dried cherry, and hazelnut with a dense crema.",
    flavorTags: ["Cocoa", "Cherry", "Hazelnut"],
    lead: "Dense, sweet espresso dialed for milk and straight shots.",
    rating: 4.4,
  },

  // ── Saudi Arabia ──
  {
    slug: "camel-step-v60-ethiopia",
    name: "Camel Step Ethiopian V60",
    roasterSlug: "camel-step",
    methodKey: "v60-hot",
    difficulty: "Intermediate",
    coffeeBeans: "Ethiopia Yirgacheffe",
    roastLevel: "Light",
    origin: "Yirgacheffe, Ethiopia",
    process: "Washed",
    tastingNotes: "Lemon tea, jasmine, and honey with a clean finish.",
    flavorTags: ["Lemon", "Jasmine", "Honey", "Clean"],
    lead: "A classic Riyadh filter profile for washed Ethiopian lots.",
    rating: 4.7,
  },
  {
    slug: "camel-step-espresso",
    name: "Camel Step House Espresso",
    roasterSlug: "camel-step",
    methodKey: "espresso",
    difficulty: "Advanced",
    coffeeBeans: "Camel Step House",
    roastLevel: "Medium",
    origin: "Brazil & Ethiopia",
    process: "Natural / Washed",
    tastingNotes: "Chocolate, date syrup, and roasted almond.",
    flavorTags: ["Chocolate", "Date", "Nutty"],
    lead: "A pioneering Saudi espresso blend for café and home machines.",
    rating: 4.6,
  },
  {
    slug: "nomad-origami-kenya",
    name: "Nomad Kenya Origami",
    roasterSlug: "nomad-coffee",
    methodKey: "origami-hot",
    difficulty: "Advanced",
    coffeeBeans: "Kenya AA",
    roastLevel: "Light",
    origin: "Kirinyaga, Kenya",
    process: "Washed",
    tastingNotes: "Tomato vine, blackcurrant, and brown sugar.",
    flavorTags: ["Blackcurrant", "Savory", "Sweet"],
    lead: "Travel-ready Origami brewing that keeps Kenya vivid.",
    rating: 4.6,
  },
  {
    slug: "nomad-aeropress",
    name: "Nomad Road AeroPress",
    roasterSlug: "nomad-coffee",
    methodKey: "aeropress",
    difficulty: "Beginner",
    coffeeBeans: "Nomad Seasonal",
    roastLevel: "Medium-light",
    origin: "Rotating",
    process: "Washed",
    tastingNotes: "Stone fruit, cocoa, and soft spice.",
    flavorTags: ["Stone fruit", "Cocoa", "Travel"],
    lead: "A compact AeroPress recipe for travel and office brewing.",
    rating: 4.4,
  },
  {
    slug: "medd-chemex-colombia",
    name: "Medd Colombia Chemex",
    roasterSlug: "medd-cafe-and-roastery",
    methodKey: "chemex",
    difficulty: "Intermediate",
    coffeeBeans: "Colombia Supremo",
    roastLevel: "Medium-light",
    origin: "Huila, Colombia",
    process: "Washed",
    tastingNotes: "Caramel, orange zest, and cocoa.",
    flavorTags: ["Caramel", "Orange", "Cocoa"],
    lead: "Jeddah Chemex clarity for washed Colombian sweetness.",
    rating: 4.5,
  },
  {
    slug: "medd-cold-brew",
    name: "Medd Coastal Cold Brew",
    roasterSlug: "medd-cafe-and-roastery",
    methodKey: "cold-brew",
    difficulty: "Beginner",
    coffeeBeans: "Medd Natural Lot",
    roastLevel: "Medium",
    origin: "Brazil / Ethiopia",
    process: "Natural",
    tastingNotes: "Cocoa, dried fig, and brown sugar.",
    flavorTags: ["Cocoa", "Fig", "Smooth"],
    lead: "An overnight cold brew built for Jeddah’s climate.",
    rating: 4.3,
  },
  {
    slug: "brew92-v60-iced-yemen",
    name: "Brew92 Yemen V60 Iced",
    roasterSlug: "brew92",
    methodKey: "v60-iced",
    difficulty: "Intermediate",
    coffeeBeans: "Yemeni Specialty Lot",
    roastLevel: "Medium-light",
    origin: "Yemen",
    process: "Natural",
    tastingNotes: "Dried apricot, cocoa, and spice over ice.",
    flavorTags: ["Apricot", "Cocoa", "Spice", "Iced"],
    lead: "A flash-brew V60 iced recipe tuned to Brew92’s 92°C philosophy.",
    rating: 4.6,
  },
  {
    slug: "brew92-kalita",
    name: "Brew92 Kalita Wave",
    roasterSlug: "brew92",
    methodKey: "kalita",
    difficulty: "Intermediate",
    coffeeBeans: "Brew92 Filter Seasonal",
    roastLevel: "Light-medium",
    origin: "East Africa / Americas",
    process: "Washed",
    tastingNotes: "Honey, red berry, and soft florals.",
    flavorTags: ["Honey", "Berry", "Floral"],
    lead: "Flat-bed Kalita brewing for even extraction and café consistency.",
    rating: 4.5,
  },
  {
    slug: "hjeen-kalita-brazil",
    name: "Hjeen Brazil Kalita",
    roasterSlug: "hjeen",
    methodKey: "kalita",
    difficulty: "Beginner",
    coffeeBeans: "Brazil Cerrado",
    roastLevel: "Medium",
    origin: "Cerrado, Brazil",
    process: "Natural",
    tastingNotes: "Milk chocolate, peanut brittle, and soft berry.",
    flavorTags: ["Chocolate", "Nutty", "Sweet"],
    lead: "A forgiving Kalita cup from Hjeen’s roaster-lab program.",
    rating: 4.3,
  },
  {
    slug: "hjeen-origami-iced",
    name: "Hjeen Origami Iced",
    roasterSlug: "hjeen",
    methodKey: "origami-iced",
    difficulty: "Intermediate",
    coffeeBeans: "Hjeen Seasonal Filter",
    roastLevel: "Light",
    origin: "Rotating",
    process: "Washed",
    tastingNotes: "Green grape, jasmine, and cane sugar over ice.",
    flavorTags: ["Grape", "Floral", "Iced"],
    lead: "Origami iced brewing with lab-level pour structure.",
    rating: 4.4,
  },

  // ── Kuwait ──
  {
    slug: "vol1-v60-ethiopia",
    name: "VOL.1 Ethiopian V60",
    roasterSlug: "vol1-roastery",
    methodKey: "v60-hot",
    difficulty: "Intermediate",
    coffeeBeans: "Ethiopia Guji",
    roastLevel: "Light",
    origin: "Guji, Ethiopia",
    process: "Washed",
    tastingNotes: "Bergamot, peach, and florals.",
    flavorTags: ["Bergamot", "Peach", "Floral"],
    lead: "Modern Kuwait City V60 brewing for washed Ethiopian lots.",
    rating: 4.6,
  },
  {
    slug: "vol1-espresso",
    name: "VOL.1 Signature Espresso",
    roasterSlug: "vol1-roastery",
    methodKey: "espresso",
    difficulty: "Advanced",
    coffeeBeans: "VOL.1 House Espresso",
    roastLevel: "Medium",
    origin: "Brazil & Ethiopia",
    process: "Natural / Washed",
    tastingNotes: "Cocoa, orange zest, and brown sugar.",
    flavorTags: ["Cocoa", "Citrus", "Sweet"],
    lead: "A modern espresso dial for Kuwait specialty cafés.",
    rating: 4.5,
  },
  {
    slug: "ark-espresso-house",
    name: "A R K House Espresso",
    roasterSlug: "ark-roasters",
    methodKey: "espresso",
    difficulty: "Intermediate",
    coffeeBeans: "A R K House Blend",
    roastLevel: "Medium",
    origin: "Multi-origin",
    process: "Natural / Washed",
    tastingNotes: "Dark chocolate, walnut, and soft spice.",
    flavorTags: ["Chocolate", "Walnut", "Spice"],
    lead: "Loring-roasted espresso for ethical single-origin programs.",
    rating: 4.4,
  },
  {
    slug: "ark-chemex",
    name: "A R K Chemex",
    roasterSlug: "ark-roasters",
    methodKey: "chemex",
    difficulty: "Intermediate",
    coffeeBeans: "Single Origin Filter",
    roastLevel: "Light-medium",
    origin: "Rotating",
    process: "Washed",
    tastingNotes: "Honey, citrus, and clean florals.",
    flavorTags: ["Honey", "Citrus", "Clean"],
    lead: "Chemex clarity for A R K’s filter offerings.",
    rating: 4.3,
  },
  {
    slug: "stockroom-cold-brew",
    name: "Stockroom Cold Brew",
    roasterSlug: "stockroom-coffee",
    methodKey: "cold-brew",
    difficulty: "Beginner",
    coffeeBeans: "Stockroom Blend",
    roastLevel: "Medium",
    origin: "Brazil & Colombia",
    process: "Natural / Washed",
    tastingNotes: "Cocoa, molasses, and soft berry.",
    flavorTags: ["Cocoa", "Molasses", "Smooth"],
    lead: "Wholesale-ready cold brew concentrate from Shuwaikh.",
    rating: 4.4,
  },
  {
    slug: "stockroom-v60-iced",
    name: "Stockroom V60 Iced",
    roasterSlug: "stockroom-coffee",
    methodKey: "v60-iced",
    difficulty: "Beginner",
    coffeeBeans: "Stockroom Filter",
    roastLevel: "Medium-light",
    origin: "Central America",
    process: "Washed",
    tastingNotes: "Orange, caramel, and soft florals over ice.",
    flavorTags: ["Orange", "Caramel", "Iced"],
    lead: "Café-friendly flash brew for Kuwait summers.",
    rating: 4.2,
  },
  {
    slug: "methods-aeropress-seasonal",
    name: "Methods Seasonal AeroPress",
    roasterSlug: "methods-academy-and-roastery",
    methodKey: "aeropress",
    difficulty: "Beginner",
    coffeeBeans: "Methods Academy Seasonal",
    roastLevel: "Medium-light",
    origin: "Rotating",
    process: "Washed",
    tastingNotes: "Red berry, cocoa, and soft florals.",
    flavorTags: ["Berry", "Cocoa", "Training"],
    lead: "An academy-friendly AeroPress used in Methods classes.",
    rating: 4.3,
  },
  {
    slug: "methods-origami-hot",
    name: "Methods Origami Hot",
    roasterSlug: "methods-academy-and-roastery",
    methodKey: "origami-hot",
    difficulty: "Intermediate",
    coffeeBeans: "Methods Filter Lot",
    roastLevel: "Light",
    origin: "East Africa",
    process: "Washed",
    tastingNotes: "Citrus, white florals, and cane sugar.",
    flavorTags: ["Citrus", "Floral", "Sweet"],
    lead: "Origami hot brewing taught on the Methods academy floor.",
    rating: 4.4,
  },

  // ── Qatar ──
  {
    slug: "flat-white-signature-espresso",
    name: "Flat White Signature Espresso",
    roasterSlug: "flat-white",
    methodKey: "espresso",
    difficulty: "Advanced",
    coffeeBeans: "Flat White House",
    roastLevel: "Medium",
    origin: "Brazil & Ethiopia",
    process: "Natural / Washed",
    tastingNotes: "Milk chocolate, caramel, and soft citrus.",
    flavorTags: ["Chocolate", "Caramel", "Milk-friendly"],
    lead: "Doha café espresso tuned for flat whites and straight shots.",
    rating: 4.6,
  },
  {
    slug: "flat-white-v60",
    name: "Flat White House V60",
    roasterSlug: "flat-white",
    methodKey: "v60-hot",
    difficulty: "Beginner",
    coffeeBeans: "Flat White Filter",
    roastLevel: "Medium-light",
    origin: "Colombia",
    process: "Washed",
    tastingNotes: "Brown sugar, orange, and soft florals.",
    flavorTags: ["Brown sugar", "Orange", "Easy"],
    lead: "Approachable V60 for home brewers in Doha.",
    rating: 4.3,
  },
  {
    slug: "vulcan-v60-colombia",
    name: "Vulcan Colombia V60",
    roasterSlug: "vulcan-coffee-roastery",
    methodKey: "v60-hot",
    difficulty: "Intermediate",
    coffeeBeans: "Organic Colombia",
    roastLevel: "Light-medium",
    origin: "Colombia",
    process: "Washed",
    tastingNotes: "Red apple, panela, and cocoa.",
    flavorTags: ["Apple", "Panela", "Cocoa"],
    lead: "Organic Colombian V60 roasted in Qatar.",
    rating: 4.5,
  },
  {
    slug: "vulcan-cold-brew",
    name: "Vulcan Cold Brew",
    roasterSlug: "vulcan-coffee-roastery",
    methodKey: "cold-brew",
    difficulty: "Beginner",
    coffeeBeans: "Vulcan Natural",
    roastLevel: "Medium",
    origin: "Brazil",
    process: "Natural",
    tastingNotes: "Chocolate, hazelnut, and dried cherry.",
    flavorTags: ["Chocolate", "Hazelnut", "Cherry"],
    lead: "Smooth immersion cold brew for Doha hospitality.",
    rating: 4.3,
  },
  {
    slug: "bon-and-bean-chemex",
    name: "Bon and Bean Chemex",
    roasterSlug: "bon-and-bean",
    methodKey: "chemex",
    difficulty: "Intermediate",
    coffeeBeans: "Air-Roasted Seasonal",
    roastLevel: "Light",
    origin: "Rotating",
    process: "Washed",
    tastingNotes: "Tea-like florals, lemon, and honey.",
    flavorTags: ["Floral", "Lemon", "Honey", "Clean"],
    lead: "Chemex clarity matched to electric air-roasted lots.",
    rating: 4.4,
  },
  {
    slug: "bon-and-bean-aeropress",
    name: "Bon and Bean AeroPress",
    roasterSlug: "bon-and-bean",
    methodKey: "aeropress",
    difficulty: "Beginner",
    coffeeBeans: "Bon and Bean Blend",
    roastLevel: "Medium-light",
    origin: "Multi-origin",
    process: "Washed",
    tastingNotes: "Cocoa, citrus, and soft spice.",
    flavorTags: ["Cocoa", "Citrus", "Easy"],
    lead: "Immersion AeroPress for eco-minded Doha brewing.",
    rating: 4.2,
  },

  // ── Bahrain ──
  {
    slug: "crust-v60-house",
    name: "Crust & Crema House V60",
    roasterSlug: "crust-and-crema",
    methodKey: "v60-hot",
    difficulty: "Beginner",
    coffeeBeans: "Crust House Filter",
    roastLevel: "Medium-light",
    origin: "Central America",
    process: "Washed",
    tastingNotes: "Caramel, citrus, and soft cocoa.",
    flavorTags: ["Caramel", "Citrus", "Cocoa"],
    lead: "Bakery-café V60 for Manama mornings.",
    rating: 4.3,
  },
  {
    slug: "crust-espresso",
    name: "Crust & Crema Espresso",
    roasterSlug: "crust-and-crema",
    methodKey: "espresso",
    difficulty: "Intermediate",
    coffeeBeans: "Crust Espresso Blend",
    roastLevel: "Medium",
    origin: "Brazil & Colombia",
    process: "Natural / Washed",
    tastingNotes: "Chocolate, biscuit, and soft berry.",
    flavorTags: ["Chocolate", "Biscuit", "Berry"],
    lead: "Milk-friendly espresso for pastry pairings.",
    rating: 4.4,
  },
  {
    slug: "bahrain-roastery-kalita",
    name: "Bahrain Roastery Kalita Wave",
    roasterSlug: "bahrain-roastery",
    methodKey: "kalita",
    difficulty: "Intermediate",
    coffeeBeans: "Wide Selection Filter Lot",
    roastLevel: "Light-medium",
    origin: "Rotating",
    process: "Washed",
    tastingNotes: "Honey, stone fruit, and clean florals.",
    flavorTags: ["Honey", "Stone fruit", "Floral"],
    lead: "Kalita Wave brewing for Bahrain Roastery’s filter range.",
    rating: 4.5,
  },
  {
    slug: "bahrain-roastery-origami-hot",
    name: "Bahrain Roastery Origami",
    roasterSlug: "bahrain-roastery",
    methodKey: "origami-hot",
    difficulty: "Advanced",
    coffeeBeans: "Microlot Filter",
    roastLevel: "Light",
    origin: "Ethiopia / Kenya rotating",
    process: "Washed",
    tastingNotes: "Bergamot, white peach, and cane sugar.",
    flavorTags: ["Bergamot", "Peach", "Sweet"],
    lead: "Origami hot brew for standout microlots.",
    rating: 4.5,
  },
  {
    slug: "black-22-cold-brew",
    name: "Black 22 Cold Brew",
    roasterSlug: "black-22",
    methodKey: "cold-brew",
    difficulty: "Beginner",
    coffeeBeans: "Black 22 House",
    roastLevel: "Medium",
    origin: "Brazil",
    process: "Natural",
    tastingNotes: "Cocoa, molasses, and soft spice.",
    flavorTags: ["Cocoa", "Molasses", "Smooth"],
    lead: "Training-room cold brew from Black 22’s micro-roastery.",
    rating: 4.3,
  },
  {
    slug: "black-22-chemex",
    name: "Black 22 Chemex",
    roasterSlug: "black-22",
    methodKey: "chemex",
    difficulty: "Intermediate",
    coffeeBeans: "Black 22 Filter",
    roastLevel: "Light-medium",
    origin: "Colombia",
    process: "Washed",
    tastingNotes: "Orange, caramel, and soft florals.",
    flavorTags: ["Orange", "Caramel", "Clean"],
    lead: "Chemex clarity for SCA-aligned training cups.",
    rating: 4.2,
  },

  // ── Oman ──
  {
    slug: "windrose-v60-ethiopia",
    name: "Windrose Ethiopian V60",
    roasterSlug: "windrose-coffee",
    methodKey: "v60-hot",
    difficulty: "Intermediate",
    coffeeBeans: "Ethiopia Washed",
    roastLevel: "Light",
    origin: "Ethiopia",
    process: "Washed",
    tastingNotes: "Jasmine, lemon, and honey.",
    flavorTags: ["Jasmine", "Lemon", "Honey"],
    lead: "Oman’s first specialty V60 — bright, clean, and sweet.",
    rating: 4.7,
  },
  {
    slug: "windrose-espresso",
    name: "Windrose House Espresso",
    roasterSlug: "windrose-coffee",
    methodKey: "espresso",
    difficulty: "Advanced",
    coffeeBeans: "Windrose Espresso",
    roastLevel: "Medium",
    origin: "Brazil & East Africa",
    process: "Natural / Washed",
    tastingNotes: "Chocolate, date, and soft citrus.",
    flavorTags: ["Chocolate", "Date", "Citrus"],
    lead: "Muscat espresso dialed for wholesale and retail consistency.",
    rating: 4.5,
  },
  {
    slug: "windrose-cold-brew",
    name: "Windrose Cold Brew",
    roasterSlug: "windrose-coffee",
    methodKey: "cold-brew",
    difficulty: "Beginner",
    coffeeBeans: "Windrose Natural",
    roastLevel: "Medium",
    origin: "Brazil",
    process: "Natural",
    tastingNotes: "Cocoa, hazelnut, and soft berry.",
    flavorTags: ["Cocoa", "Hazelnut", "Berry"],
    lead: "Fridge-ready cold brew for Muscat hospitality.",
    rating: 4.4,
  },
  {
    slug: "windrose-aeropress",
    name: "Windrose AeroPress",
    roasterSlug: "windrose-coffee",
    methodKey: "aeropress",
    difficulty: "Beginner",
    coffeeBeans: "Windrose Seasonal",
    roastLevel: "Medium-light",
    origin: "Rotating",
    process: "Washed",
    tastingNotes: "Stone fruit, cocoa, and soft florals.",
    flavorTags: ["Stone fruit", "Cocoa", "Easy"],
    lead: "Immersion AeroPress for home brewers across Oman.",
    rating: 4.3,
  },
];
