import type { BrewMethodId, BrewMethodProfile } from "@/lib/converter/types";

/**
 * Deterministic extraction profiles for every brew method the Universal
 * Recipe Converter supports (Phase 17.2). Ranges are documented,
 * reasonable approximations drawn from common specialty-coffee brewing
 * guidance -- good enough to drive believable, consistent conversions,
 * not a substitute for a barista's own dialing-in.
 *
 * `ratio` is grams of water per gram of coffee (16 = "1:16"). `grind` is
 * the normalized 0-10 scale from `grind-scale.ts`.
 */
export const BREW_METHOD_PROFILES: Record<BrewMethodId, BrewMethodProfile> = {
  v60: {
    id: "v60",
    category: "pourOver",
    ratio: { min: 15, max: 17, default: 16 },
    temperatureC: { min: 92, max: 96, default: 94 },
    grind: { min: 3.5, max: 5, default: 4.2 },
    brewTimeSeconds: { min: 150, max: 210, default: 180 },
    defaultDoseG: 15,
    supportsBloom: true,
    bloomMultiplier: 2.5,
    defaultBloomTimeSeconds: 30,
    supportsPours: true,
    defaultPoursCount: 3,
  },
  origami: {
    id: "origami",
    category: "pourOver",
    // Fluted, fast-flowing dripper -- runs a touch faster than V60 with a similar grind window.
    ratio: { min: 15, max: 17, default: 16 },
    temperatureC: { min: 92, max: 96, default: 94 },
    grind: { min: 3.3, max: 4.8, default: 4 },
    brewTimeSeconds: { min: 140, max: 200, default: 165 },
    defaultDoseG: 15,
    supportsBloom: true,
    bloomMultiplier: 2.5,
    defaultBloomTimeSeconds: 30,
    supportsPours: true,
    defaultPoursCount: 4,
  },
  kalitaWave: {
    id: "kalitaWave",
    category: "pourOver",
    // Flat bed evens out extraction, so more frequent, smaller pours than a V60.
    ratio: { min: 15, max: 17, default: 16 },
    temperatureC: { min: 92, max: 96, default: 94 },
    grind: { min: 3.5, max: 5, default: 4.3 },
    brewTimeSeconds: { min: 170, max: 220, default: 195 },
    defaultDoseG: 15,
    supportsBloom: true,
    bloomMultiplier: 2.5,
    defaultBloomTimeSeconds: 35,
    supportsPours: true,
    defaultPoursCount: 5,
  },
  chemex: {
    id: "chemex",
    category: "pourOver",
    // Thick proprietary filter slows drawdown, so grind runs coarser than V60 for the same brew time.
    ratio: { min: 15, max: 17, default: 16 },
    temperatureC: { min: 92, max: 96, default: 94 },
    grind: { min: 5, max: 6.5, default: 5.6 },
    brewTimeSeconds: { min: 210, max: 270, default: 240 },
    defaultDoseG: 30,
    supportsBloom: true,
    bloomMultiplier: 2.5,
    defaultBloomTimeSeconds: 45,
    supportsPours: true,
    defaultPoursCount: 3,
  },
  aeropress: {
    id: "aeropress",
    category: "immersion",
    // Pressure + short contact time means a stronger ratio and lower temperature than gravity pour-over.
    ratio: { min: 12, max: 16, default: 14 },
    temperatureC: { min: 80, max: 90, default: 85 },
    grind: { min: 3, max: 5, default: 4 },
    brewTimeSeconds: { min: 60, max: 150, default: 90 },
    defaultDoseG: 16,
    supportsBloom: true,
    bloomMultiplier: 1.5,
    defaultBloomTimeSeconds: 20,
    supportsPours: true,
    defaultPoursCount: 1,
  },
  cleverDripper: {
    id: "cleverDripper",
    category: "immersion",
    // Full steep with a valve release -- sits between French press and pour-over.
    ratio: { min: 14, max: 16, default: 15 },
    temperatureC: { min: 90, max: 94, default: 92 },
    grind: { min: 4.5, max: 6, default: 5 },
    brewTimeSeconds: { min: 180, max: 240, default: 210 },
    defaultDoseG: 18,
    supportsBloom: true,
    bloomMultiplier: 2,
    defaultBloomTimeSeconds: 30,
    supportsPours: false,
    defaultPoursCount: 1,
  },
  frenchPress: {
    id: "frenchPress",
    category: "immersion",
    // Full immersion through a metal mesh needs a coarse grind to avoid sediment/over-extraction.
    ratio: { min: 12, max: 15, default: 13 },
    temperatureC: { min: 92, max: 96, default: 94 },
    grind: { min: 7, max: 8.5, default: 7.5 },
    brewTimeSeconds: { min: 210, max: 270, default: 240 },
    defaultDoseG: 20,
    supportsBloom: false,
    bloomMultiplier: 0,
    defaultBloomTimeSeconds: 0,
    supportsPours: false,
    defaultPoursCount: 1,
  },
  orea: {
    id: "orea",
    category: "pourOver",
    // Lightweight, high-flow conical dripper -- similar territory to V60/Origami.
    ratio: { min: 15, max: 17, default: 16 },
    temperatureC: { min: 92, max: 96, default: 94 },
    grind: { min: 3.5, max: 5, default: 4.4 },
    brewTimeSeconds: { min: 150, max: 200, default: 170 },
    defaultDoseG: 15,
    supportsBloom: true,
    bloomMultiplier: 2.5,
    defaultBloomTimeSeconds: 30,
    supportsPours: true,
    defaultPoursCount: 3,
  },
  aprilBrewer: {
    id: "aprilBrewer",
    category: "pourOver",
    // Flat-bottomed like Kalita Wave, but slightly more forgiving on pour technique.
    ratio: { min: 15, max: 17, default: 16 },
    temperatureC: { min: 92, max: 96, default: 94 },
    grind: { min: 3.8, max: 5.2, default: 4.6 },
    brewTimeSeconds: { min: 160, max: 210, default: 185 },
    defaultDoseG: 16,
    supportsBloom: true,
    bloomMultiplier: 2.5,
    defaultBloomTimeSeconds: 35,
    supportsPours: true,
    defaultPoursCount: 3,
  },
  xbloomStudio: {
    id: "xbloomStudio",
    category: "pourOver",
    // Automated pour-over with programmable multi-stage pours -- V60-like extraction, wider usable temperature range.
    ratio: { min: 15, max: 17, default: 16 },
    temperatureC: { min: 85, max: 96, default: 93 },
    grind: { min: 3.5, max: 5, default: 4.5 },
    brewTimeSeconds: { min: 150, max: 210, default: 180 },
    defaultDoseG: 15,
    supportsBloom: true,
    bloomMultiplier: 2.5,
    defaultBloomTimeSeconds: 30,
    supportsPours: true,
    defaultPoursCount: 3,
  },
  xbloomOmni: {
    id: "xbloomOmni",
    category: "pourOver",
    // Precision flow control supports a finer grind and more granular pour staging than Studio/Original.
    ratio: { min: 15, max: 17, default: 16 },
    temperatureC: { min: 85, max: 96, default: 93 },
    grind: { min: 3.2, max: 4.8, default: 4.2 },
    brewTimeSeconds: { min: 150, max: 210, default: 180 },
    defaultDoseG: 15,
    supportsBloom: true,
    bloomMultiplier: 2.5,
    defaultBloomTimeSeconds: 30,
    supportsPours: true,
    defaultPoursCount: 4,
  },
  xbloomOriginal: {
    id: "xbloomOriginal",
    category: "pourOver",
    ratio: { min: 15, max: 17, default: 16 },
    temperatureC: { min: 85, max: 96, default: 93 },
    grind: { min: 3.5, max: 5.2, default: 4.6 },
    brewTimeSeconds: { min: 150, max: 210, default: 180 },
    defaultDoseG: 15,
    supportsBloom: true,
    bloomMultiplier: 2.5,
    defaultBloomTimeSeconds: 30,
    supportsPours: true,
    defaultPoursCount: 3,
  },
  espresso: {
    id: "espresso",
    category: "pressurized",
    // Concentrated, pressurized extraction: tight ratio, very fine grind, short shot time.
    ratio: { min: 1.5, max: 2.5, default: 2 },
    temperatureC: { min: 90, max: 96, default: 93 },
    grind: { min: 0.3, max: 1.5, default: 0.8 },
    brewTimeSeconds: { min: 22, max: 32, default: 27 },
    defaultDoseG: 18,
    supportsBloom: false,
    bloomMultiplier: 0,
    defaultBloomTimeSeconds: 0,
    supportsPours: false,
    defaultPoursCount: 0,
  },
  coldBrew: {
    id: "coldBrew",
    category: "coldBrew",
    // Long, cold steep needs a coarse grind and a concentrate-strength ratio to avoid over-extraction/muddiness.
    ratio: { min: 7, max: 9, default: 8 },
    temperatureC: { min: 4, max: 22, default: 20 },
    grind: { min: 8.5, max: 10, default: 9.2 },
    brewTimeSeconds: { min: 43200, max: 86400, default: 64800 },
    defaultDoseG: 100,
    supportsBloom: false,
    bloomMultiplier: 0,
    defaultBloomTimeSeconds: 0,
    supportsPours: false,
    defaultPoursCount: 0,
  },
};
