/**
 * Regenerates supabase/migrations/20260809030300_seed_gulf_recipe_library.sql
 * from the TypeScript Gulf recipe library (121 recipes).
 *
 * Usage: npx tsx scripts/generate-gulf-recipe-seed.mts
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  assertGulfRecipeLibraryIntegrity,
  buildGulfRecipeLibrary,
} from "../lib/data/directory/seeds/recipe-library";
import { getGulfRoasterSeedBySlug } from "../lib/data/directory/seeds/gulf-roasters";

const OUT = resolve(
  "supabase/migrations/20260809030300_seed_gulf_recipe_library.sql",
);

function sqlString(value: string | null | undefined): string {
  if (value == null) return "null";
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlTextArray(values: string[]): string {
  if (values.length === 0) return "'{}'::text[]";
  return `array[${values.map(sqlString).join(",")}]::text[]`;
}

function scaleToTen(value: number): number {
  return Math.max(1, Math.min(10, Math.round(value / 10)));
}

function brewingMethodSlug(brewMethod: string): string {
  const map: Record<string, string> = {
    V60: "v60",
    Chemex: "chemex",
    Aeropress: "aeropress",
    Espresso: "espresso",
    "Cold Brew": "cold-brew",
    "French Press": "french-press",
    Origami: "origami",
    Kalita: "kalita",
  };
  return map[brewMethod] ?? brewMethod.toLowerCase().replace(/\s+/g, "-");
}

const recipes = buildGulfRecipeLibrary();
assertGulfRecipeLibraryIntegrity(recipes);

const lines: string[] = [
  "-- Seed the BrewAtlas Gulf Recipe Library (121 recipes).",
  "-- Source: lib/data/directory/seeds/gulf-recipes-data.ts + recipe-methods.ts",
  "-- Idempotent via recipes.slug upsert + child-table replace.",
  "-- Generated by scripts/generate-gulf-recipe-seed.mts — do not hand-edit.",
  "",
  "do $$",
  "declare",
  "  v_recipe_id uuid;",
  "  v_roaster_id uuid;",
  "  v_country_id uuid;",
  "  v_city_id uuid;",
  "  v_method_id uuid;",
  "begin",
  "",
];

for (const recipe of recipes) {
  const roaster = getGulfRoasterSeedBySlug(recipe.roasterSlug);
  if (!roaster) {
    throw new Error(`Missing roaster ${recipe.roasterSlug}`);
  }

  const methodSlug = brewingMethodSlug(recipe.brewMethod);
  const fp = recipe.flavorProfile;
  const tastingNotes = recipe.brewingTips
    ? `${recipe.tastingNotes}`
    : recipe.tastingNotes;

  lines.push(`  -- ${recipe.slug}`);
  lines.push(
    `  select id into v_roaster_id from public.roasters where slug = ${sqlString(recipe.roasterSlug)} limit 1;`,
  );
  lines.push(
    `  select id into v_country_id from public.countries where slug = ${sqlString(recipe.countrySlug)} limit 1;`,
  );
  lines.push(
    `  select ci.id into v_city_id from public.cities ci where ci.country_id = v_country_id and ci.name = ${sqlString(recipe.city)} limit 1;`,
  );
  lines.push(
    `  select id into v_method_id from public.brewing_methods where slug = ${sqlString(methodSlug)} limit 1;`,
  );
  lines.push(`  if v_roaster_id is null then`);
  lines.push(
    `    raise exception 'Missing roaster slug %', ${sqlString(recipe.roasterSlug)};`,
  );
  lines.push(`  end if;`);
  lines.push(``);
  lines.push(`  insert into public.recipes (`);
  lines.push(`    title, slug, description, cover_image_url, difficulty,`);
  lines.push(`    tasting_notes, featured, premium_only, published, status,`);
  lines.push(`    recipe_kind, verification_status, serving_style,`);
  lines.push(`    roaster_id, country_id, city_id, brewing_method_id,`);
  lines.push(`    brew_method, is_iced, rating, coffee_beans, roast_level,`);
  lines.push(`    bean_origin, process, roast_date_label, producer, variety,`);
  lines.push(`    brewing_tips, sweetness, acidity, body, bitterness,`);
  lines.push(
    `    flavor_sweetness, flavor_acidity, flavor_body, flavor_bitterness, flavor_finish,`,
  );
  lines.push(`    similar_slugs, estimated_brew_time, total_brew_time, grind_size,`);
  lines.push(`    ratio, grinder_setting, water_recommendation, equipment_notes`);
  lines.push(`  ) values (`);
  lines.push(`    ${sqlString(recipe.name)},`);
  lines.push(`    ${sqlString(recipe.slug)},`);
  lines.push(`    ${sqlString(recipe.lead)},`);
  lines.push(`    ${sqlString(recipe.image)},`);
  lines.push(`    ${sqlString(recipe.difficulty)},`);
  lines.push(`    ${sqlString(tastingNotes)},`);
  lines.push(`    ${recipe.featured},`);
  lines.push(`    false,`);
  lines.push(`    true,`);
  lines.push(`    'published',`);
  lines.push(`    'official',`);
  lines.push(`    'verified',`);
  lines.push(`    ${sqlString(recipe.isIced ? "iced" : "hot")},`);
  lines.push(`    v_roaster_id,`);
  lines.push(`    v_country_id,`);
  lines.push(`    v_city_id,`);
  lines.push(`    v_method_id,`);
  lines.push(`    ${sqlString(recipe.brewMethod)},`);
  lines.push(`    ${recipe.isIced},`);
  lines.push(`    ${recipe.rating},`);
  lines.push(`    ${sqlString(recipe.coffeeBeans)},`);
  lines.push(`    ${sqlString(recipe.roastLevel)},`);
  lines.push(`    ${sqlString(recipe.origin)},`);
  lines.push(`    ${sqlString(recipe.process)},`);
  lines.push(`    ${sqlString(recipe.roastDate)},`);
  lines.push(`    ${sqlString(recipe.producer)},`);
  lines.push(`    ${sqlString(recipe.variety)},`);
  lines.push(`    ${sqlString(recipe.brewingTips)},`);
  lines.push(`    ${scaleToTen(fp.sweetness)},`);
  lines.push(`    ${scaleToTen(fp.acidity)},`);
  lines.push(`    ${scaleToTen(fp.body)},`);
  lines.push(`    ${scaleToTen(fp.bitterness)},`);
  lines.push(`    ${fp.sweetness},`);
  lines.push(`    ${fp.acidity},`);
  lines.push(`    ${fp.body},`);
  lines.push(`    ${fp.bitterness},`);
  lines.push(`    ${fp.finish},`);
  lines.push(`    ${sqlTextArray(recipe.similarSlugs)},`);
  lines.push(`    ${sqlString(recipe.brewTime)},`);
  lines.push(`    ${sqlString(recipe.totalBrewTime)},`);
  lines.push(`    ${sqlString(recipe.grindSize)},`);
  lines.push(`    ${sqlString(recipe.ratio)},`);
  lines.push(`    ${sqlString(recipe.grindSize)},`);
  lines.push(`    ${sqlString(recipe.water)},`);
  lines.push(`    ${sqlString(recipe.brewer)}`);
  lines.push(`  )`);
  lines.push(`  on conflict (slug) do update set`);
  lines.push(`    title = excluded.title,`);
  lines.push(`    description = excluded.description,`);
  lines.push(`    cover_image_url = excluded.cover_image_url,`);
  lines.push(`    difficulty = excluded.difficulty,`);
  lines.push(`    tasting_notes = excluded.tasting_notes,`);
  lines.push(`    featured = excluded.featured,`);
  lines.push(`    published = true,`);
  lines.push(`    status = 'published',`);
  lines.push(`    recipe_kind = 'official',`);
  lines.push(`    verification_status = 'verified',`);
  lines.push(`    serving_style = excluded.serving_style,`);
  lines.push(`    roaster_id = excluded.roaster_id,`);
  lines.push(`    country_id = excluded.country_id,`);
  lines.push(`    city_id = excluded.city_id,`);
  lines.push(`    brewing_method_id = excluded.brewing_method_id,`);
  lines.push(`    brew_method = excluded.brew_method,`);
  lines.push(`    is_iced = excluded.is_iced,`);
  lines.push(`    rating = excluded.rating,`);
  lines.push(`    coffee_beans = excluded.coffee_beans,`);
  lines.push(`    roast_level = excluded.roast_level,`);
  lines.push(`    bean_origin = excluded.bean_origin,`);
  lines.push(`    process = excluded.process,`);
  lines.push(`    roast_date_label = excluded.roast_date_label,`);
  lines.push(`    producer = excluded.producer,`);
  lines.push(`    variety = excluded.variety,`);
  lines.push(`    brewing_tips = excluded.brewing_tips,`);
  lines.push(`    sweetness = excluded.sweetness,`);
  lines.push(`    acidity = excluded.acidity,`);
  lines.push(`    body = excluded.body,`);
  lines.push(`    bitterness = excluded.bitterness,`);
  lines.push(`    flavor_sweetness = excluded.flavor_sweetness,`);
  lines.push(`    flavor_acidity = excluded.flavor_acidity,`);
  lines.push(`    flavor_body = excluded.flavor_body,`);
  lines.push(`    flavor_bitterness = excluded.flavor_bitterness,`);
  lines.push(`    flavor_finish = excluded.flavor_finish,`);
  lines.push(`    similar_slugs = excluded.similar_slugs,`);
  lines.push(`    estimated_brew_time = excluded.estimated_brew_time,`);
  lines.push(`    total_brew_time = excluded.total_brew_time,`);
  lines.push(`    grind_size = excluded.grind_size,`);
  lines.push(`    ratio = excluded.ratio,`);
  lines.push(`    grinder_setting = excluded.grinder_setting,`);
  lines.push(`    water_recommendation = excluded.water_recommendation,`);
  lines.push(`    equipment_notes = excluded.equipment_notes,`);
  lines.push(`    updated_at = now()`);
  lines.push(`  returning id into v_recipe_id;`);
  lines.push(``);
  lines.push(`  delete from public.recipe_steps where recipe_id = v_recipe_id;`);
  lines.push(`  delete from public.recipe_equipment where recipe_id = v_recipe_id;`);
  lines.push(`  delete from public.recipe_flavor_notes where recipe_id = v_recipe_id;`);
  lines.push(`  delete from public.recipe_brew_variables where recipe_id = v_recipe_id;`);

  for (const [index, step] of recipe.steps.entries()) {
    lines.push(`  insert into public.recipe_steps (`);
    lines.push(
      `    recipe_id, step_key, pour_number, water_amount, time_label, notes,`,
    );
    lines.push(`    at_seconds, duration_seconds, sort_order`);
    lines.push(
      `  ) values (v_recipe_id, ${sqlString(step.id)}, ${step.pourNumber}, ${sqlString(step.waterAmount)}, ${sqlString(step.timeLabel)}, ${sqlString(step.notes)}, ${step.atSeconds}, ${step.durationSeconds}, ${index});`,
    );
  }

  for (const [index, item] of recipe.equipment.entries()) {
    lines.push(
      `  insert into public.recipe_equipment (recipe_id, name, detail, sort_order) values (v_recipe_id, ${sqlString(item.name)}, ${sqlString(item.detail)}, ${index});`,
    );
  }

  for (const [index, note] of recipe.flavorTags.entries()) {
    lines.push(
      `  insert into public.recipe_flavor_notes (recipe_id, note, sort_order) values (v_recipe_id, ${sqlString(note)}, ${index});`,
    );
  }

  const brewVars: Array<[string, string]> = [
    ["dose", recipe.dose],
    ["waterAmount", recipe.waterAmount],
    ["temperature", recipe.temperature],
    ["ratio", recipe.ratio],
    ["grindSize", recipe.grindSize],
    ["bloom", recipe.bloom],
    ["brewTime", recipe.brewTime],
    ["totalBrewTime", recipe.totalBrewTime],
    ["water", recipe.water],
    ["grinder", recipe.grinder],
    ["brewer", recipe.brewer],
    ["filter", recipe.filter],
  ];
  if (recipe.tds) brewVars.push(["tds", recipe.tds]);
  if (recipe.extractionYield) {
    brewVars.push(["extractionYield", recipe.extractionYield]);
  }

  for (const [index, [key, value]] of brewVars.entries()) {
    lines.push(
      `  insert into public.recipe_brew_variables (recipe_id, key, value, sort_order) values (v_recipe_id, ${sqlString(key)}, ${sqlString(value)}, ${index});`,
    );
  }

  lines.push(``);
}

lines.push(`end $$;`);
lines.push(``);

writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${recipes.length} recipes to ${OUT}`);
