import type { RecipePersonalizationLabels } from "@/app/components/recipes/personalization/recipe-personalization-controls";

type PersonalizationDictionary = {
  customizeTitle: string;
  roastersRecipeLabel: string;
  yourBrewLabel: string;
  yourCustomizedIcedBrewLabel: string;
  originalRecipeLabel: string;
  servingStyleLabel: string;
  hotOption: string;
  icedOption: string;
  officialBadge: string;
  personalizedBadge: string;
  roasterRecommendedBadge: string;
  resetCta: string;
  brewMethodLabel: string;
  coffeeDoseLabel: string;
  brewRatioLabel: string;
  customValue: string;
  guidanceTitle: string;
  saveMyRecipeCta: string;
  duplicateRecipeCta: string;
  shareRecipeCta: string;
  resetToRoasterCta: string;
  totalWaterLabel: string;
  hotWaterLabel: string;
  iceLabel: string;
  pourPrefix: string;
  poursLabel: string;
  poursCountLabel: string;
  temperatureLabel: string;
  officialTemperatureLabel: string;
  resetTemperatureCta: string;
  grindSizeLabel: string;
  grindFinerLabel: string;
  grindCoarserLabel: string;
  grindOfficialLabel: string;
  rpmLabel: string;
  openInXbloomCta: string;
  tasteDirectionTitle: string;
  tasteGuidanceNote: string;
  tasteSweetness: string;
  tasteAcidity: string;
  tasteBody: string;
  tasteBitterness: string;
  tasteExtraction: string;
  tasteSummaryFuller: string;
  tasteSummaryBrighter: string;
  tasteSummarySofter: string;
  tasteSummaryBalanced: string;
  tasteSummaryIced: string;
  tasteTempUpExtraction: string;
  tasteTempUpBody: string;
  tasteTempUpBitterness: string;
  tasteTempUpAcidity: string;
  tasteTempDownExtraction: string;
  tasteTempDownAcidity: string;
  tasteTempDownBody: string;
  tasteTempDownBitterness: string;
  tastePoursUpAgitation: string;
  tastePoursUpExtraction: string;
  tastePoursDownAgitation: string;
  tastePoursDownExtraction: string;
  tasteRatioUpDilution: string;
  tasteRatioUpClarity: string;
  tasteRatioDownStrength: string;
  tasteRatioDownIntensity: string;
  tasteDoseUpStrength: string;
  tasteDoseDownStrength: string;
  tasteGrindFinerExtraction: string;
  tasteGrindFinerBitterness: string;
  tasteGrindCoarserExtraction: string;
  tasteGrindCoarserAcidity: string;
  tasteIcedDilution: string;
};

/** Map i18n recipePersonalization dictionary → control labels. */
export function personalizationControlLabels(
  dictionary: PersonalizationDictionary,
): RecipePersonalizationLabels {
  return {
    customizeTitle: dictionary.customizeTitle,
    roastersRecipeLabel: dictionary.roastersRecipeLabel,
    yourBrewLabel: dictionary.yourBrewLabel,
    yourCustomizedIcedBrewLabel: dictionary.yourCustomizedIcedBrewLabel,
    originalRecipeLabel: dictionary.originalRecipeLabel,
    servingStyleLabel: dictionary.servingStyleLabel,
    hotOption: dictionary.hotOption,
    icedOption: dictionary.icedOption,
    officialBadge: dictionary.officialBadge,
    personalizedBadge: dictionary.personalizedBadge,
    roasterRecommendedBadge: dictionary.roasterRecommendedBadge,
    resetCta: dictionary.resetCta,
    brewMethodLabel: dictionary.brewMethodLabel,
    coffeeDoseLabel: dictionary.coffeeDoseLabel,
    brewRatioLabel: dictionary.brewRatioLabel,
    customValue: dictionary.customValue,
    guidanceTitle: dictionary.guidanceTitle,
    saveMyRecipeCta: dictionary.saveMyRecipeCta,
    duplicateRecipeCta: dictionary.duplicateRecipeCta,
    shareRecipeCta: dictionary.shareRecipeCta,
    resetToRoasterCta: dictionary.resetToRoasterCta,
    totalWaterLabel: dictionary.totalWaterLabel,
    hotWaterLabel: dictionary.hotWaterLabel,
    iceLabel: dictionary.iceLabel,
    pourPrefix: dictionary.pourPrefix,
    poursLabel: dictionary.poursLabel,
    poursCountLabel: dictionary.poursCountLabel,
    temperatureLabel: dictionary.temperatureLabel,
    officialTemperatureLabel: dictionary.officialTemperatureLabel,
    resetTemperatureCta: dictionary.resetTemperatureCta,
    grindSizeLabel: dictionary.grindSizeLabel,
    grindFinerLabel: dictionary.grindFinerLabel,
    grindCoarserLabel: dictionary.grindCoarserLabel,
    grindOfficialLabel: dictionary.grindOfficialLabel,
    rpmLabel: dictionary.rpmLabel,
    openInXbloomCta: dictionary.openInXbloomCta,
    tasteDirectionTitle: dictionary.tasteDirectionTitle,
    tasteGuidanceNote: dictionary.tasteGuidanceNote,
    tasteSweetness: dictionary.tasteSweetness,
    tasteAcidity: dictionary.tasteAcidity,
    tasteBody: dictionary.tasteBody,
    tasteBitterness: dictionary.tasteBitterness,
    tasteExtraction: dictionary.tasteExtraction,
    tasteSummaryFuller: dictionary.tasteSummaryFuller,
    tasteSummaryBrighter: dictionary.tasteSummaryBrighter,
    tasteSummarySofter: dictionary.tasteSummarySofter,
    tasteSummaryBalanced: dictionary.tasteSummaryBalanced,
    tasteSummaryIced: dictionary.tasteSummaryIced,
    tasteTempUpExtraction: dictionary.tasteTempUpExtraction,
    tasteTempUpBody: dictionary.tasteTempUpBody,
    tasteTempUpBitterness: dictionary.tasteTempUpBitterness,
    tasteTempUpAcidity: dictionary.tasteTempUpAcidity,
    tasteTempDownExtraction: dictionary.tasteTempDownExtraction,
    tasteTempDownAcidity: dictionary.tasteTempDownAcidity,
    tasteTempDownBody: dictionary.tasteTempDownBody,
    tasteTempDownBitterness: dictionary.tasteTempDownBitterness,
    tastePoursUpAgitation: dictionary.tastePoursUpAgitation,
    tastePoursUpExtraction: dictionary.tastePoursUpExtraction,
    tastePoursDownAgitation: dictionary.tastePoursDownAgitation,
    tastePoursDownExtraction: dictionary.tastePoursDownExtraction,
    tasteRatioUpDilution: dictionary.tasteRatioUpDilution,
    tasteRatioUpClarity: dictionary.tasteRatioUpClarity,
    tasteRatioDownStrength: dictionary.tasteRatioDownStrength,
    tasteRatioDownIntensity: dictionary.tasteRatioDownIntensity,
    tasteDoseUpStrength: dictionary.tasteDoseUpStrength,
    tasteDoseDownStrength: dictionary.tasteDoseDownStrength,
    tasteGrindFinerExtraction: dictionary.tasteGrindFinerExtraction,
    tasteGrindFinerBitterness: dictionary.tasteGrindFinerBitterness,
    tasteGrindCoarserExtraction: dictionary.tasteGrindCoarserExtraction,
    tasteGrindCoarserAcidity: dictionary.tasteGrindCoarserAcidity,
    tasteIcedDilution: dictionary.tasteIcedDilution,
  };
}
