-- Production starter seed for the BrewAtlas Gulf Roaster Directory.
-- Source of truth mirror: lib/data/directory/seeds/gulf-roasters.ts
-- Idempotent upsert by slug. Real specialty roasters only.

alter table public.roasters
  add column if not exists specialty text,
  add column if not exists founded_year integer;

comment on column public.roasters.specialty is
  'Short specialty focus label for directory cards and roaster pages.';

comment on column public.roasters.founded_year is
  'Founding year when known; null when unverified.';

-- Reconcile older catalog rows before slug upsert:
-- 1) free seed slugs held by non-matching names
-- 2) attach canonical slugs to rows that already share the seed name
with seed_names (name, slug) as (
  values
  ('RAW Coffee Company', 'raw-coffee-company'),
  ('The Espresso Lab', 'the-espresso-lab'),
  ('Seven Fortunes', 'seven-fortunes'),
  ('Cypher Roastery', 'cypher-roastery'),
  ('Gold Box Roastery', 'gold-box-roastery'),
  ('Nightjar Coffee', 'nightjar-coffee'),
  ('Boon Coffee Roasters', 'boon-coffee-roasters'),
  ('Mokha 1450', 'mokha-1450'),
  ('Specialty Batch Coffee', 'specialty-batch-coffee'),
  ('Liwa Coffee Roastery', 'liwa-coffee-roastery'),
  ('Absolute Coffee', 'absolute-coffee'),
  ('South Roastery', 'south-roastery'),
  ('Camel Step', 'camel-step'),
  ('By The Way', 'by-the-way'),
  ('Hjeen', 'hjeen'),
  ('Medd Cafe & Roastery', 'medd-cafe-and-roastery'),
  ('Caffeine Lab', 'caffeine-lab'),
  ('12 Cups', 'twelve-cups'),
  ('Drip On', 'drip-on'),
  ('Suwaa Roastery', 'suwaa-roastery'),
  ('Brew92', 'brew92'),
  ('Elixir Bunn', 'elixir-bunn'),
  ('Sulalat', 'sulalat'),
  ('IDMI Coffee Roasting Co', 'idmi-coffee'),
  ('Trivali Roastery', 'trivali-roastery'),
  ('Black Knight Roastery', 'black-knight-roastery'),
  ('Black Horse Roastery', 'black-horse-roastery'),
  ('Ananas Roastery', 'ananas-roastery'),
  ('Kiffa Roastery', 'kiffa-roastery'),
  ('C&B Roastery', 'c-and-b-roastery'),
  ('VOL.1 Roastery', 'vol1-roastery'),
  ('A R K Roasters', 'ark-roasters'),
  ('Stockroom Coffee', 'stockroom-coffee'),
  ('Methods Academy and Roastery', 'methods-academy-and-roastery'),
  ('Jumo Coffee Roasters', 'jumo-coffee-roasters'),
  ('Vulcan Coffee Roastery', 'vulcan-coffee-roastery'),
  ('Bon and Bean', 'bon-and-bean'),
  ('Honoroast', 'honoroast'),
  ('Crust & Crema', 'crust-and-crema'),
  ('Bahrain Roastery', 'bahrain-roastery'),
  ('Black 22', 'black-22'),
  ('Windrose Coffee', 'windrose-coffee'),
  ('Dar Al Bun', 'dar-al-bun')
),
freed as (
  update public.roasters as occupied
  set
    slug = occupied.slug || '-pre-gulf-' || substr(occupied.id::text, 1, 8),
    updated_at = now()
  from seed_names
  where occupied.slug = seed_names.slug
    and occupied.name is distinct from seed_names.name
  returning occupied.id
)
update public.roasters as existing
set
  slug = seed_names.slug,
  updated_at = now()
from seed_names
where existing.name = seed_names.name
  and existing.slug is distinct from seed_names.slug;

-- Keep fictional UAE brand placeholders out of the verified Gulf directory.
update public.roasters
set
  verified = false,
  featured = false,
  published = false,
  updated_at = now()
where slug in (
  'dune-and-ember-roasting-co',
  'seven-sands-coffee',
  'majlis-roasters',
  'pearl-coast-coffee-traders',
  'al-sadu-coffee-house',
  'falcons-rest-roastery'
);

insert into public.roasters (
  name,
  slug,
  country,
  emirate,
  city,
  website,
  instagram,
  description,
  specialty,
  founded_year,
  featured,
  is_uae,
  published,
  verified,
  logo_url,
  banner_image_url
)
values
  (
    'RAW Coffee Company',
    'raw-coffee-company',
    'United Arab Emirates',
    'Dubai',
    'Al Quoz',
    'https://rawcoffeecompany.com',
    'https://instagram.com/rawcoffeecompany',
    'Home-grown UAE specialty coffee roaster and SCA training campus in Al Quoz, Dubai. Owners Kim Thompson and Matt Toogood source, roast, and supply premium coffee for wholesale and retail across the region.',
    'Single origin & SCA training',
    2011,
    true,
    true,
    true,
    true,
    '/images/gulf-heritage/raw-coffee-company.webp',
    '/images/gulf-heritage/countries/uae.webp'
  ),
  (
    'The Espresso Lab',
    'the-espresso-lab',
    'United Arab Emirates',
    'Dubai',
    'Dubai',
    'https://theespressolab.com',
    'https://instagram.com/theespressolab',
    'Dubai-born artisan coffee company founded by Emirati entrepreneur Ibrahim Al Mallouhi, sourcing microlots and roasting across Dubai Design District, Al Quoz, Abu Dhabi, and Sharjah.',
    'Microlot roasting & café program',
    2014,
    false,
    true,
    true,
    true,
    '/images/gulf-heritage/the-espresso-lab.webp',
    '/images/gulf-heritage/countries/uae.webp'
  ),
  (
    'Seven Fortunes',
    'seven-fortunes',
    'United Arab Emirates',
    'Dubai',
    'Al Quoz',
    'https://www.sevenfortunes.com',
    'https://instagram.com/sevenfortunes',
    'Dubai specialty roaster in Al Quoz providing premium coffee beans, SCA training, and café equipment consulting including La Marzocco distribution.',
    'Filter roasting & SCA training',
    null,
    false,
    true,
    true,
    true,
    '/images/gulf-heritage/seven-fortunes.webp',
    '/images/gulf-heritage/countries/uae.webp'
  ),
  (
    'Cypher Roastery',
    'cypher-roastery',
    'United Arab Emirates',
    'Dubai',
    'Al Quoz',
    'https://www.bycypher.com',
    'https://instagram.com/bycypher',
    'Dubai specialty roaster in Al Quoz sourcing, grading, and roasting premium coffee with a commitment to fair trade, transparency, and social responsibility.',
    'Transparent sourcing & experimental lots',
    null,
    false,
    true,
    true,
    true,
    '/images/gulf-heritage/cypher-roastery.webp',
    '/images/gulf-heritage/countries/uae.webp'
  ),
  (
    'Gold Box Roastery',
    'gold-box-roastery',
    'United Arab Emirates',
    'Dubai',
    'Al Quoz',
    'https://goldboxroastery.com',
    'https://instagram.com/goldboxroastery',
    'Dubai specialty roaster in Al Quoz roasting green coffee for hotels, cafés, and retail customers across the United Arab Emirates.',
    'Wholesale & hospitality roasting',
    null,
    false,
    true,
    true,
    true,
    '/images/gulf-heritage/gold-box-roastery.webp',
    '/images/gulf-heritage/countries/uae.webp'
  ),
  (
    'Nightjar Coffee',
    'nightjar-coffee',
    'United Arab Emirates',
    'Dubai',
    'Al Quoz',
    'https://www.nightjar.coffee',
    'https://instagram.com/nightjarcoffee',
    'Award-winning Dubai roaster at Alserkal Avenue specializing in artisanal coffee roasting, cold brew production, and café operations.',
    'Artisan roasting & cold brew',
    null,
    false,
    true,
    true,
    true,
    '/images/gulf-heritage/nightjar-coffee.webp',
    '/images/gulf-heritage/countries/uae.webp'
  ),
  (
    'Boon Coffee Roasters',
    'boon-coffee-roasters',
    'United Arab Emirates',
    'Dubai',
    'JLT',
    'https://booncoffee.com',
    'https://instagram.com/booncoffee',
    'UAE specialty roaster founded by Orit Mohammed in 2013, sourcing single-origin Arabica directly from Ethiopia with wholesale across the GCC.',
    'Ethiopian single-origin focus',
    2013,
    false,
    true,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/uae.webp'
  ),
  (
    'Mokha 1450',
    'mokha-1450',
    'United Arab Emirates',
    'Dubai',
    'Al Wasl',
    'https://www.mokha1450.com',
    'https://instagram.com/mokha1450',
    'Luxury UAE specialty coffee brand in Dubai sourcing direct-trade coffees from women-owned farms, with rare origins from Yemen, Ethiopia, and beyond.',
    'Direct-trade luxury specialty',
    null,
    false,
    true,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/uae.webp'
  ),
  (
    'Specialty Batch Coffee',
    'specialty-batch-coffee',
    'United Arab Emirates',
    'Dubai',
    'Dubai',
    'https://specialtybatch.com',
    'https://instagram.com/specialtybatch',
    'Dubai craft coffee roaster and full-service partner supplying wholesale beans, Synesso and Bentwood equipment, training, and technical support across the UAE.',
    'Craft roasting & café support',
    null,
    false,
    true,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/uae.webp'
  ),
  (
    'Liwa Coffee Roastery',
    'liwa-coffee-roastery',
    'United Arab Emirates',
    'Dubai',
    'Dubai',
    'https://liwacoffee.com',
    'https://instagram.com/liwacoffee',
    'UAE specialty coffee roaster supplying premium single-origin and Arabic coffee beans to retail and wholesale customers across Dubai and the GCC.',
    'Single-origin & Arabic coffee',
    null,
    false,
    true,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/uae.webp'
  ),
  (
    'Absolute Coffee',
    'absolute-coffee',
    'United Arab Emirates',
    'Dubai',
    'Dubai',
    'https://absolute.coffee',
    'https://instagram.com/absolutecoffeeroasters',
    'UAE specialty coffee roaster focused on small-batch roasting and fruit-forward, co-fermented specialty lots, with retail shipping across the United Arab Emirates.',
    'Small-batch exotic & co-fermented lots',
    null,
    false,
    true,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/uae.webp'
  ),
  (
    'South Roastery',
    'south-roastery',
    'United Arab Emirates',
    'Sharjah',
    'Sharjah',
    'https://southcoffee.ae',
    'https://instagram.com/south_roastery',
    'Sharjah specialty coffee roastery founded in 2022, roasting locally for wholesale and retail, with barista training and cupping programs through South Academy.',
    'Wholesale roasting & South Academy',
    2022,
    false,
    true,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/uae.webp'
  ),
  (
    'Camel Step',
    'camel-step',
    'Saudi Arabia',
    null,
    'Riyadh',
    'https://camelstep.com',
    'https://instagram.com/camelstep',
    'Riyadh specialty coffee roaster founded in 2013, widely credited with pioneering Saudi Arabia''s specialty coffee market and roasting premium global origins.',
    'Pioneer Saudi specialty roasting',
    2013,
    true,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'By The Way',
    'by-the-way',
    'Saudi Arabia',
    null,
    'Riyadh',
    'https://btw.sa',
    'https://instagram.com/btw.coffee',
    'Riyadh specialty coffee roastery since 2019 sourcing fine single-origin beans from Brazil, Ethiopia, Colombia, and Costa Rica.',
    'Single-origin filter & espresso',
    2019,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'Hjeen',
    'hjeen',
    'Saudi Arabia',
    null,
    'Riyadh',
    'https://hjeen.com',
    'https://instagram.com/hjeen',
    'Riyadh specialty coffee roastery blending innovation and tradition, with an integrated roaster-lab and SCA-certified roasting team.',
    'Roaster-lab innovation',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'Medd Cafe & Roastery',
    'medd-cafe-and-roastery',
    'Saudi Arabia',
    null,
    'Jeddah',
    'https://meddcoffee.com',
    'https://instagram.com/meddcoffee',
    'Jeddah specialty roastery since 2015 roasting carefully selected crops from the world''s finest farms to the highest international standards.',
    'Jeddah filter & café roasting',
    2015,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'Caffeine Lab',
    'caffeine-lab',
    'Saudi Arabia',
    null,
    'Jeddah',
    'https://caffeinelab.me',
    'https://instagram.com/caffeinelab',
    'Jeddah specialty coffee roastery, café, and retail pioneer founded in 2014, committed to direct trade, roasting, and barista education across Saudi Arabia.',
    'Direct trade & barista education',
    2014,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    '12 Cups',
    'twelve-cups',
    'Saudi Arabia',
    null,
    'Riyadh',
    'https://12cups.com.sa',
    'https://instagram.com/12cups.sa',
    'Riyadh specialty coffee company founded in 2013, distributing premium roasted beans and brewing equipment across the Kingdom.',
    'Retail roasting & equipment',
    2013,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'Drip On',
    'drip-on',
    'Saudi Arabia',
    null,
    'Jeddah',
    'https://driponcoffeesa.com',
    'https://instagram.com/driponcoffee',
    'Jeddah specialty coffee roastery established in 2019, sourcing beans globally and roasting fresh in the Kingdom for retail and wholesale.',
    'Fresh local roasting',
    2019,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'Suwaa Roastery',
    'suwaa-roastery',
    'Saudi Arabia',
    null,
    'Jeddah',
    'https://suwaaroastery.com',
    'https://instagram.com/suwaaroastery',
    'Jeddah specialty coffee roastery founded in 2017, selecting global crops and designing roasting profiles for espresso, filter, and Saudi coffee.',
    'Espresso, filter & Saudi coffee',
    2017,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'Brew92',
    'brew92',
    'Saudi Arabia',
    null,
    'Jeddah',
    'https://www.brew92.com',
    'https://instagram.com/brew92',
    'Jeddah specialty café and roastery founded in 2016, brewing at 92°C with an SCA-certified team sourcing 100% specialty-grade Arabica.',
    'SCA-certified café roasting',
    2016,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'Elixir Bunn',
    'elixir-bunn',
    'Saudi Arabia',
    null,
    'Riyadh',
    'https://elixirbunn.com',
    'https://instagram.com/elixirbunn',
    'Riyadh specialty coffee roaster offering international single origins and regional Saudi coffee blends through retail and wholesale.',
    'International & Saudi blends',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'Sulalat',
    'sulalat',
    'Saudi Arabia',
    null,
    'Riyadh',
    'https://sulalat.com',
    'https://instagram.com/sulalat',
    'Saudi specialty coffee company focused on carefully sourced lots, including Saudi Arabian origins, with retail coffee and brewing tools for cafés and home brewers.',
    'Saudi origin & specialty retail',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'IDMI Coffee Roasting Co',
    'idmi-coffee',
    'Saudi Arabia',
    null,
    'Riyadh',
    'https://idmicoffee.com',
    'https://instagram.com/idmicoffee',
    'Saudi specialty coffee roasting company selecting high-quality lots and roasting for distinctive cup profiles across retail and wholesale channels.',
    'Specialty roasting & retail',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'Trivali Roastery',
    'trivali-roastery',
    'Saudi Arabia',
    null,
    'Arar',
    'https://trivali.sa',
    'https://instagram.com/tri.vali',
    'Saudi specialty coffee roastery roasting distinctive single-origin and experimental lots for retail and café customers across the Kingdom.',
    'Fruit-forward specialty lots',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'Black Knight Roastery',
    'black-knight-roastery',
    'Saudi Arabia',
    null,
    'Al Khobar',
    'https://b-k.coffee',
    'https://instagram.com/bk.coffee',
    'Al Khobar specialty coffee brand roasting premium international origins and Saudi coffee lots for retail, drip, and café channels across the Kingdom and GCC.',
    'Premium specialty & Saudi coffee',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'Black Horse Roastery',
    'black-horse-roastery',
    'Saudi Arabia',
    null,
    'Al Khobar',
    'https://blackhorse.sa',
    'https://instagram.com/BLACKHORSE_KSA',
    'Al Khobar specialty coffee roastery and café program roasting single-origin lots and house blends for retail and hospitality customers in Saudi Arabia.',
    'Specialty roasting & café program',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'Ananas Roastery',
    'ananas-roastery',
    'Saudi Arabia',
    null,
    'Dammam',
    'https://ananasroastery.com',
    'https://instagram.com/ananas_roastery',
    'Dammam specialty coffee roastery founded in 2021, roasting a wide range of approachable specialty lots and blends for retail customers across Saudi Arabia.',
    'Accessible specialty roasting',
    2021,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'Kiffa Roastery',
    'kiffa-roastery',
    'Saudi Arabia',
    null,
    'Medina',
    'https://kiffa.sa',
    'https://instagram.com/kiffa.sa',
    'Medina specialty coffee roastery roasting international origins and Saudi coffee, with retail beans, café service, and brewing accessories for home and hospitality customers.',
    'Saudi-made specialty roasting',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'C&B Roastery',
    'c-and-b-roastery',
    'Saudi Arabia',
    null,
    'Tabuk',
    'https://cup8beans.com',
    'https://instagram.com/cup8beans',
    'Tabuk specialty coffee café and roastery (Cup & Beans) selecting global and Saudi origins to roast for café service, retail beans, and franchise partners across the Kingdom.',
    'Café roasting & Saudi origins',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/saudi-arabia.webp'
  ),
  (
    'VOL.1 Roastery',
    'vol1-roastery',
    'Kuwait',
    null,
    'Kuwait City',
    'https://vol1kuwait.com',
    'https://instagram.com/vol1kuwait',
    'Kuwait specialty coffee bar and micro-roastery founded by Nora Al Roumi in 2013, helping establish third-wave coffee culture in Kuwait with small-batch roasting and café programs.',
    'Micro-roastery & specialty bar',
    2013,
    true,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/kuwait.webp'
  ),
  (
    'A R K Roasters',
    'ark-roasters',
    'Kuwait',
    null,
    'Kuwait City',
    'https://ark.com.kw',
    'https://instagram.com/ark.kw',
    'Kuwait specialty roastery roasting ethically sourced single-origin coffees on a Loring S7, part of the A R K brand founded in 2016.',
    'Ethical single-origin roasting',
    2016,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/kuwait.webp'
  ),
  (
    'Stockroom Coffee',
    'stockroom-coffee',
    'Kuwait',
    null,
    'Shuwaikh',
    'https://stockroomcoffee.com',
    'https://instagram.com/stockroomcoffee',
    'Kuwait specialty coffee roastery in Shuwaikh Industrial Area since 2017, supplying beans, equipment, training, and consultancy to cafés and businesses.',
    'Wholesale, training & consultancy',
    2017,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/kuwait.webp'
  ),
  (
    'Methods Academy and Roastery',
    'methods-academy-and-roastery',
    'Kuwait',
    null,
    'Kuwait City',
    'https://methods.coffee',
    'https://instagram.com/methods.coffee',
    'Kuwait specialty coffee roastery and academy offering small-batch roasted beans, barista training, and wholesale distribution.',
    'Academy & small-batch roasting',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/kuwait.webp'
  ),
  (
    'Jumo Coffee Roasters',
    'jumo-coffee-roasters',
    'Kuwait',
    null,
    'Kuwait City',
    'https://jumocoffee.com',
    'https://instagram.com/jumocoffee',
    'Kuwait artisanal coffee roastery craft-roasting specialty beans for cafés, restaurants, and international wholesale markets.',
    'Artisanal wholesale roasting',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/kuwait.webp'
  ),
  (
    'Vulcan Coffee Roastery',
    'vulcan-coffee-roastery',
    'Qatar',
    null,
    'Doha',
    'https://vulcanroastery.com',
    'https://instagram.com/vulcanroastery',
    'Doha specialty coffee roastery sourcing high-quality organic beans from farmers worldwide and roasting in Qatar.',
    'Organic single-origin roasting',
    null,
    true,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/qatar.webp'
  ),
  (
    'Bon and Bean',
    'bon-and-bean',
    'Qatar',
    null,
    'Doha',
    'https://bonandbean.com',
    'https://instagram.com/bonandbean',
    'Doha eco-friendly specialty coffee roaster using electric air roasting to produce single-origin coffees and handcrafted blends.',
    'Electric air roasting',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/qatar.webp'
  ),
  (
    'Honoroast',
    'honoroast',
    'Qatar',
    null,
    'Doha',
    'https://www.honoroast.qa',
    'https://instagram.com/honoroast.qa',
    'Doha specialty coffee roastery founded in 2019, roasting fresh single-origin beans with direct farmer relationships and SCA-certified roasting.',
    'Direct-trade single origins',
    2019,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/qatar.webp'
  ),
  (
    'Crust & Crema',
    'crust-and-crema',
    'Bahrain',
    null,
    'Manama',
    'https://www.wooholdings.com/crust-crema',
    'https://instagram.com/crustandcrema',
    'Bahrain specialty café and micro-roastery since 2015, roasting 100% Arabica single origins and house blends as an SCA member pioneering third-wave coffee in the Kingdom.',
    'In-house micro-roastery & café',
    2015,
    true,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/bahrain.webp'
  ),
  (
    'Bahrain Roastery',
    'bahrain-roastery',
    'Bahrain',
    null,
    'Manama',
    'https://bahrainroastery.com',
    'https://instagram.com/bahrainroastery',
    'Bahrain artisan coffee roastery with one of the GCC''s widest whole-bean selections, roasting fresh for retail and hospitality across the region.',
    'Wide-selection artisan roasting',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/bahrain.webp'
  ),
  (
    'Black 22',
    'black-22',
    'Bahrain',
    null,
    'Manama',
    'https://black22bh.com',
    'https://instagram.com/black22bh',
    'Bahrain specialty coffee bar and micro-roastery offering house-roasted beans, SCA-aligned training, and retail coffee.',
    'Specialty bar & micro-roasting',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/bahrain.webp'
  ),
  (
    'Windrose Coffee',
    'windrose-coffee',
    'Oman',
    null,
    'Muscat',
    'https://www.windrosecoffee.com',
    'https://instagram.com/windrosecoffee',
    'Oman''s first specialty coffee roastery in Muscat, focusing on ethically sourced, consistently roasted coffees for wholesale and retail.',
    'Oman''s pioneering specialty roasting',
    null,
    true,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/oman.webp'
  ),
  (
    'Dar Al Bun',
    'dar-al-bun',
    'Oman',
    null,
    'Muscat',
    'https://daralbun.net',
    'https://instagram.com/daralbun',
    'Omani specialty coffee roaster and retailer offering carefully selected single-origin lots and brewing equipment for home and café customers.',
    'Specialty retail roasting',
    null,
    false,
    false,
    true,
    true,
    null,
    '/images/gulf-heritage/countries/oman.webp'
  )
on conflict (slug) do update set
  name = excluded.name,
  country = excluded.country,
  emirate = excluded.emirate,
  city = excluded.city,
  website = excluded.website,
  instagram = excluded.instagram,
  description = excluded.description,
  specialty = excluded.specialty,
  founded_year = excluded.founded_year,
  featured = excluded.featured,
  is_uae = excluded.is_uae,
  published = excluded.published,
  verified = excluded.verified,
  logo_url = excluded.logo_url,
  banner_image_url = excluded.banner_image_url,
  updated_at = now();

-- Ensure countries exist (safe if already seeded).
insert into public.countries (slug, name, flag, sort_order)
values
  ('uae', 'United Arab Emirates', '🇦🇪', 1),
  ('saudi-arabia', 'Saudi Arabia', '🇸🇦', 2),
  ('kuwait', 'Kuwait', '🇰🇼', 3),
  ('qatar', 'Qatar', '🇶🇦', 4),
  ('bahrain', 'Bahrain', '🇧🇭', 5),
  ('oman', 'Oman', '🇴🇲', 6)
on conflict (slug) do update
set
  name = excluded.name,
  flag = excluded.flag,
  sort_order = excluded.sort_order,
  published = true,
  updated_at = now();

-- Backfill country_id from legacy text country.
update public.roasters r
set country_id = c.id
from public.countries c
where r.country is not null
  and r.country = c.name
  and (r.country_id is distinct from c.id);

-- Seed / refresh cities from verified Gulf directory roasters.
insert into public.cities (country_id, name, slug)
select
  c.id,
  r.city,
  trim(both '-' from lower(regexp_replace(trim(r.city), '[^a-zA-Z0-9]+', '-', 'g')))
from public.countries c
join public.roasters r on r.country_id = c.id
where r.verified = true
  and r.published = true
  and r.city is not null
  and trim(r.city) <> ''
group by c.id, r.city
on conflict (country_id, slug) do nothing;

-- Backfill city_id.
update public.roasters r
set city_id = ci.id
from public.cities ci
where r.country_id = ci.country_id
  and r.city is not null
  and r.city = ci.name
  and (r.city_id is distinct from ci.id);
