-- Official BrewAtlas Gulf Roasters Directory seed.
-- Inserts ~30 verified specialty coffee roasters across UAE, Saudi Arabia,
-- Kuwait, Qatar, Bahrain, and Oman. Idempotent via slug upsert; safe to re-run.

insert into public.roasters (
  name,
  slug,
  country,
  emirate,
  city,
  website,
  instagram,
  description,
  featured,
  is_uae,
  published,
  verified,
  logo_url,
  banner_image_url
)
values
  -- United Arab Emirates (~10)
  (
    'RAW Coffee Company',
    'raw-coffee-company',
    'United Arab Emirates',
    'Dubai',
    'Al Quoz',
    'https://rawcoffeecompany.com',
    'https://instagram.com/rawcoffeecompany',
    'Home-grown UAE specialty coffee roaster and SCA training campus in Al Quoz, Dubai. Owners Kim Thompson and Matt Toogood source, roast, and supply premium coffee for wholesale and retail across the region.',
    false,
    true,
    true,
    true,
    null,
    null
  ),
  (
    'The Espresso Lab',
    'the-espresso-lab',
    'United Arab Emirates',
    'Dubai',
    'Dubai',
    'https://theespressolab.com',
    'https://instagram.com/theespressolab',
    'Dubai-born artisan coffee company founded by Emirati entrepreneur Ibrahim Al Mallouhi, sourcing microlots and roasting across Dubai Design District, Al Quoz, Abu Dhabi, and Sharjah.',
    false,
    true,
    true,
    true,
    null,
    null
  ),
  (
    'Seven Fortunes',
    'seven-fortunes',
    'United Arab Emirates',
    'Dubai',
    'Al Quoz',
    'https://www.sevenfortunes.com',
    'https://instagram.com/sevenfortunes',
    'Dubai specialty roaster in Al Quoz providing premium coffee beans, SCA training, and café equipment consulting including La Marzocco distribution.',
    false,
    true,
    true,
    true,
    null,
    null
  ),
  (
    'Cypher Roastery',
    'cypher-roastery',
    'United Arab Emirates',
    'Dubai',
    'Al Quoz',
    'https://www.bycypher.com',
    'https://instagram.com/bycypher',
    'Dubai specialty roaster in Al Quoz sourcing, grading, and roasting premium coffee with a commitment to fair trade, transparency, and social responsibility.',
    false,
    true,
    true,
    true,
    null,
    null
  ),
  (
    'Gold Box Roastery',
    'gold-box-roastery',
    'United Arab Emirates',
    'Dubai',
    'Al Quoz',
    'https://goldboxroastery.com',
    'https://instagram.com/goldboxroastery',
    'Dubai specialty roaster in Al Quoz roasting green coffee for hotels, cafés, and retail customers across the United Arab Emirates.',
    false,
    true,
    true,
    true,
    null,
    null
  ),
  (
    'Nightjar Coffee',
    'nightjar-coffee',
    'United Arab Emirates',
    'Dubai',
    'Al Quoz',
    'https://www.nightjar.coffee',
    'https://instagram.com/nightjarcoffee',
    'Award-winning Dubai roaster at Alserkal Avenue specializing in artisanal coffee roasting, cold brew production, and café operations.',
    false,
    true,
    true,
    true,
    null,
    null
  ),
  (
    'Boon Coffee Roasters',
    'boon-coffee-roasters',
    'United Arab Emirates',
    'Dubai',
    'JLT',
    'https://booncoffee.com',
    'https://instagram.com/booncoffee',
    'UAE specialty roaster founded by Orit Mohammed in 2013, sourcing single-origin Arabica directly from Ethiopia with wholesale across the GCC.',
    false,
    true,
    true,
    true,
    null,
    null
  ),
  (
    'Mokha 1450',
    'mokha-1450',
    'United Arab Emirates',
    'Dubai',
    'Al Wasl',
    'https://www.mokha1450.com',
    'https://instagram.com/mokha1450',
    'Luxury UAE specialty coffee brand in Dubai sourcing direct-trade coffees from women-owned farms, with rare origins from Yemen, Ethiopia, and beyond.',
    false,
    true,
    true,
    true,
    null,
    null
  ),
  (
    'Specialty Batch Coffee',
    'specialty-batch-coffee',
    'United Arab Emirates',
    'Dubai',
    'Dubai',
    'https://specialtybatch.com',
    'https://instagram.com/specialtybatch',
    'Dubai craft coffee roaster and full-service partner supplying wholesale beans, Synesso and Bentwood equipment, training, and technical support across the UAE.',
    false,
    true,
    true,
    true,
    null,
    null
  ),
  (
    'Liwa Coffee Roastery',
    'liwa-coffee-roastery',
    'United Arab Emirates',
    'Dubai',
    'Dubai',
    'https://liwacoffee.com',
    'https://instagram.com/liwacoffee',
    'UAE specialty coffee roaster supplying premium single-origin and Arabic coffee beans to retail and wholesale customers across Dubai and the GCC.',
    false,
    true,
    true,
    true,
    null,
    null
  ),

  -- Saudi Arabia (~10)
  (
    'Camel Step',
    'camel-step',
    'Saudi Arabia',
    null,
    'Riyadh',
    'https://camelstep.com',
    'https://instagram.com/camelstep',
    'Riyadh specialty coffee roaster founded in 2013, widely credited with pioneering Saudi Arabia''s specialty coffee market and roasting premium global origins.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'By The Way',
    'by-the-way',
    'Saudi Arabia',
    null,
    'Riyadh',
    'https://btw.sa',
    'https://instagram.com/btw.coffee',
    'Riyadh specialty coffee roastery since 2019 sourcing fine single-origin beans from Brazil, Ethiopia, Colombia, and Costa Rica.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'Hjeen',
    'hjeen',
    'Saudi Arabia',
    null,
    'Riyadh',
    'https://hjeen.com',
    'https://instagram.com/hjeen',
    'Riyadh specialty coffee roastery blending innovation and tradition, with an integrated roaster-lab and SCA-certified roasting team.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'Medd Cafe & Roastery',
    'medd-cafe-and-roastery',
    'Saudi Arabia',
    null,
    'Jeddah',
    'https://meddcoffee.com',
    'https://instagram.com/meddcoffee',
    'Jeddah specialty roastery since 2015 roasting carefully selected crops from the world''s finest farms to the highest international standards.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'Caffeine Lab',
    'caffeine-lab',
    'Saudi Arabia',
    null,
    'Jeddah',
    'https://caffeinelab.me',
    'https://instagram.com/caffeinelab',
    'Jeddah specialty coffee roastery, café, and retail pioneer founded in 2014, committed to direct trade, roasting, and barista education across Saudi Arabia.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    '12 Cups',
    'twelve-cups',
    'Saudi Arabia',
    null,
    'Riyadh',
    'https://12cups.com.sa',
    'https://instagram.com/12cups.sa',
    'Riyadh specialty coffee company founded in 2013, distributing premium roasted beans and brewing equipment across the Kingdom.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'Drip On',
    'drip-on',
    'Saudi Arabia',
    null,
    'Jeddah',
    'https://driponcoffeesa.com',
    'https://instagram.com/driponcoffee',
    'Jeddah specialty coffee roastery established in 2019, sourcing beans globally and roasting fresh in the Kingdom for retail and wholesale.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'Suwaa Roastery',
    'suwaa-roastery',
    'Saudi Arabia',
    null,
    'Jeddah',
    'https://suwaaroastery.com',
    'https://instagram.com/suwaaroastery',
    'Jeddah specialty coffee roastery founded in 2017, selecting global crops and designing roasting profiles for espresso, filter, and Saudi coffee.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'Brew92',
    'brew92',
    'Saudi Arabia',
    null,
    'Jeddah',
    'https://www.brew92.com',
    'https://instagram.com/brew92',
    'Jeddah specialty café and roastery founded in 2016, brewing at 92°C with an SCA-certified team sourcing 100% specialty-grade Arabica.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'Elixir Bunn',
    'elixir-bunn',
    'Saudi Arabia',
    null,
    'Riyadh',
    'https://elixirbunn.com',
    'https://instagram.com/elixirbunn',
    'Riyadh specialty coffee roaster offering international single origins and regional Saudi coffee blends through retail and wholesale.',
    false,
    false,
    true,
    true,
    null,
    null
  ),

  -- Kuwait (~4)
  (
    'A R K Roasters',
    'ark-roasters',
    'Kuwait',
    null,
    'Kuwait City',
    'https://ark.com.kw',
    'https://instagram.com/ark.kw',
    'Kuwait specialty roastery roasting ethically sourced single-origin coffees on a Loring S7, part of the A R K brand founded in 2016.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'Stockroom Coffee',
    'stockroom-coffee',
    'Kuwait',
    null,
    'Shuwaikh',
    'https://stockroomcoffee.com',
    'https://instagram.com/stockroomcoffee',
    'Kuwait specialty coffee roastery in Shuwaikh Industrial Area since 2017, supplying beans, equipment, training, and consultancy to cafés and businesses.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'Methods Academy and Roastery',
    'methods-academy-and-roastery',
    'Kuwait',
    null,
    'Kuwait City',
    'https://methods.coffee',
    'https://instagram.com/methods.coffee',
    'Kuwait specialty coffee roastery and academy offering small-batch roasted beans, barista training, and wholesale distribution.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'Jumo Coffee Roasters',
    'jumo-coffee-roasters',
    'Kuwait',
    null,
    'Kuwait City',
    'https://jumocoffee.com',
    'https://instagram.com/jumocoffee',
    'Kuwait artisanal coffee roastery craft-roasting specialty beans for cafés, restaurants, and international wholesale markets.',
    false,
    false,
    true,
    true,
    null,
    null
  ),

  -- Qatar (~3)
  (
    'Vulcan Coffee Roastery',
    'vulcan-coffee-roastery',
    'Qatar',
    null,
    'Doha',
    'https://vulcanroastery.com',
    'https://instagram.com/vulcanroastery',
    'Doha specialty coffee roastery sourcing high-quality organic beans from farmers worldwide and roasting in Qatar.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'Bon and Bean',
    'bon-and-bean',
    'Qatar',
    null,
    'Doha',
    'https://bonandbean.com',
    'https://instagram.com/bonandbean',
    'Doha eco-friendly specialty coffee roaster using electric air roasting to produce single-origin coffees and handcrafted blends.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'Honoroast',
    'honoroast',
    'Qatar',
    null,
    'Doha',
    'https://www.honoroast.qa',
    'https://instagram.com/honoroast.qa',
    'Doha specialty coffee roastery founded in 2019, roasting fresh single-origin beans with direct farmer relationships and SCA-certified roasting.',
    false,
    false,
    true,
    true,
    null,
    null
  ),

  -- Bahrain (~2)
  (
    'Bahrain Roastery',
    'bahrain-roastery',
    'Bahrain',
    null,
    'Manama',
    'https://bahrainroastery.com',
    'https://instagram.com/bahrainroastery',
    'Bahrain artisan coffee roastery with one of the GCC''s widest whole-bean selections, roasting fresh for retail and hospitality across the region.',
    false,
    false,
    true,
    true,
    null,
    null
  ),
  (
    'Black 22',
    'black-22',
    'Bahrain',
    null,
    'Manama',
    'https://black22bh.com',
    'https://instagram.com/black22bh',
    'Bahrain specialty coffee bar and micro-roastery offering house-roasted beans, SCA-aligned training, and retail coffee.',
    false,
    false,
    true,
    true,
    null,
    null
  ),

  -- Oman (~1)
  (
    'Windrose Coffee',
    'windrose-coffee',
    'Oman',
    null,
    'Muscat',
    'https://www.windrosecoffee.com',
    'https://instagram.com/windrosecoffee',
    'Oman''s first specialty coffee roastery in Muscat, focusing on ethically sourced, consistently roasted coffees for wholesale and retail.',
    false,
    false,
    true,
    true,
    null,
    null
  )
on conflict (slug) do update set
  name = excluded.name,
  country = excluded.country,
  emirate = excluded.emirate,
  city = excluded.city,
  website = excluded.website,
  instagram = excluded.instagram,
  description = excluded.description,
  featured = excluded.featured,
  is_uae = excluded.is_uae,
  published = excluded.published,
  verified = excluded.verified,
  logo_url = excluded.logo_url,
  banner_image_url = excluded.banner_image_url,
  updated_at = now();
