-- recipe_insight_warnings: the intelligent warnings generated alongside a
-- recipe's calculated insights (e.g. "water too hot", "grind too fine").
-- Normalized into their own rows (one per triggered warning) rather than a
-- jsonb array, matching the rest of the schema's conventions.

create table public.recipe_insight_warnings (
  id uuid primary key default gen_random_uuid(),
  recipe_insight_id uuid not null references public.recipe_insights (id) on delete cascade,
  code text not null check (
    code in (
      'water_too_hot',
      'water_too_cold',
      'grind_too_fine',
      'grind_too_coarse',
      'ratio_too_strong',
      'ratio_too_weak',
      'bloom_too_short',
      'bloom_too_long',
      'excessive_agitation'
    )
  ),
  severity text not null default 'warning' check (severity in ('info', 'warning', 'critical')),
  message text not null,
  created_at timestamptz not null default now(),
  constraint recipe_insight_warnings_insight_code_key unique (recipe_insight_id, code)
);

comment on table public.recipe_insight_warnings is
  'Intelligent warnings generated by the Recipe Intelligence Engine for a recipe_insights row, e.g. water/grind/ratio/bloom/agitation issues.';

create index recipe_insight_warnings_insight_id_idx on public.recipe_insight_warnings (recipe_insight_id);

alter table public.recipe_insight_warnings enable row level security;

-- A warning is visible exactly when its parent insight (and in turn its
-- recipe) is.
create policy "Recipe insight warnings are viewable when their insight is"
  on public.recipe_insight_warnings for select
  using (
    exists (
      select 1 from public.recipe_insights i
      join public.recipes r on r.id = i.recipe_id
      where i.id = recipe_insight_warnings.recipe_insight_id
        and (r.published = true or r.author_id = auth.uid() or public.is_admin())
    )
  );

create policy "Authors can manage warnings on their own recipe insights"
  on public.recipe_insight_warnings for all
  using (
    exists (
      select 1 from public.recipe_insights i
      join public.recipes r on r.id = i.recipe_id
      where i.id = recipe_insight_warnings.recipe_insight_id and r.author_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.recipe_insights i
      join public.recipes r on r.id = i.recipe_id
      where i.id = recipe_insight_warnings.recipe_insight_id and r.author_id = auth.uid()
    )
  );

create policy "Admins can manage all recipe insight warnings"
  on public.recipe_insight_warnings for all
  using (public.is_admin())
  with check (public.is_admin());
